# .SMR to CSV

This notebook will focus on transformming the .smr summary file that is the output from the IFSM model and making it first into a textfile. After which point we will then convert this into either several csv files one for each table with the names of each stored in a json files that we can then access for information on specifi information... or we will do something else and have everything in a json or different excel sheets...



NEED TO AUTOMATTICALLY DETERMINE START AND END FOR EACH TABLE


THEN USE THOSE LENGTHS TO AID IN SPLITTING....


THE TITLES WILL BE NEEDED.....

In [1]:
import numpy as np
import pandas as pd

In [185]:
tables = pd.read_fwf("IFSM_srm1.txt", header=None, sep='\s*\|\s*', engine='python', skip_blank_lines=True)
tables[163]

KeyError: 163

In [186]:
f = open("IFSM_srm1.txt", 'r')
# get all lines
lines = f.readlines()
lines

['\n',
 '\n',
 '\tAverage crop yields and nutritive contents over a 25 year analysis of a 85 ha\n',
 '\tdairy farm.\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\t               --------- Preharvest --------     ----------- Postharvest -------\n',
 '\t                 Yield       Crude                   Yield       Crude\n',
 '\t               (t DM/ha)    Protein      NDF       (t DM/ha)    Protein      NDF\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\tGRASS, 85 ha\n',
 '\t  Cutting 1       3.92       15.6       44.8          3.69       16.0       47.7\n',
 '\t  Cutting 2       2.56       18.6       42.8          2.46       18.8       44.2\n',
 '\t    Total         6.48       16.8       44.1          6.15       17.4       46.0\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\n',
 '\n',
 '\tAnnual feed production and use for a 25 year analysis of a dairy farm with 200\n',
 '\tcows and 129 other stock on 85 hectares of land.\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\t                                                 Unit        Mean          SD\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\t  High-quality silage production                 t DM         150          19\n',
 '\t  Grazed forage consumed                         t DM         320          42\n',
 '\t  Forage purchased                               t DM         641          53\n',
 '\t  Grain purchased                                t DM         554           6\n',
 '\t  Soybean meal, 44% purchased                    t DM           6           4\n',
 '\t  User defined feed purchased                    t DM          28           3\n',
 '\t  Mineral and vitamin mix purchased              t DM          10           0\n',
 '\t  Milk production                               L/cow        8419          15\n',
 '\t  Fat and protein corrected milk production    kg/cow        9890          17\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\n',
 '\n',
 '\tNutrients available, used, and lost to the environment for a 25 year analysis of\n',
 '\ta farm with 200 cows and 129 other stock on 85 hectares of land.\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\t                                                 Unit        Mean          SD\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\t  Nitrogen imported to farm                     kg/ha       479.2        17.5\n',
 '\t  Nitrogen exported from farm                   kg/ha       124.1         0.0\n',
 '\t  Nitrogen lost by volatilization               kg/ha       128.9         8.2\n',
 '\t  Nitrogen lost by leaching                     kg/ha       136.8        28.4\n',
 '\t  Nitrogen lost by de/nitrification             kg/ha        47.6         5.4\n',
 '\t  Nitrogen lost by runoff                       kg/ha         0.3         0.2\n',
 '\t  Nitrogen concentration in leachate             ppm          9.3         2.3\n',
 '\t  Whole-farm excess nitrogen                    kg/ha        47.1        29.8\n',
 '\n',
 '\t  Phosphorous imported to farm                  kg/ha        50.8         1.7\n',
 '\t  Phosphorous exported from farm                kg/ha        17.5         0.0\n',
 '\t  Phosphorous available on farm                 kg/ha        49.2         4.2\n',
 '\t  Phosphorous loss in runoff and leachate       kg/ha         1.1         0.7\n',
 '\t  Whole-farm excess phosphorus                  kg/ha        32.3         1.7\n',
 '\n',
 '\t  Potassium imported to farm                    kg/ha       187.4        10.1\n',
 '\t  Potassium exported from farm                  kg/ha        25.6         0.0\n',
 '\t  Potassium available on farm                   kg/ha       314.8        27.2\n',
 '\t  Potassium loss through runoff                 kg/ha        15.7         1.4\n',
 '\t  Whole-farm excess potassium                   kg/ha       146.1        10.4\n',
 '\n',
 '\t  Carbon imported to farm                       kg/ha     15031.7       934.7\n',
 '\t  Carbon exported from farm                     kg/ha      1441.5         0.0\n',
 '\t  Carbon loss as carbon dioxide                 kg/ha     13237.6       935.9\n',
 '\t  Carbon loss as methane                        kg/ha       351.3         4.2\n',
 '\t  Carbon loss through runoff                    kg/ha         1.3         0.8\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\n',
 '\n',
 '\tAnnual production costs and return to management for a 25 year analysis of a \n',
 '\tfarm with 200 cows and 129 other stock on 85 hectares of land.\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\t                                                 Unit        Mean          SD\n',
 '\t__________________________________________________________________________________\n',
 '\n',
 '\t  Equipment cost                                   $        41976         246\n',
 '\t  Facilities cost                                  $        86883         446\n',
 '\t  Energy cost                                      $        20027         122\n',
 '\t  Labor cost                                       $        67797         285\n',
 '\t  Seed, fertilizer and chemical cost               $        14863           0\n',
 '\t  Net purchased feed and bedding cost              $       279079        9281\n',
 '\t  Animal purchase and livestock expense            $        74625           0\n',
 '\t  Milk hauling and marketing fees                  $        33677          59\n',
 '\t  Property tax                                     $         5979           0\n',
 '\n',
 '\t  Income from milk sales                           $       673539        1173\n',
 '\t  Income from animal sales                         $        53648           0\n',
 '\n',
 '\t  Return to management and unpaid factors          $       102281        9381\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\n',
 '\n',
 '\tDaily and annual emissions of important gaseous compounds for a dairy farm with\n',
 '\t200 cows and 129 other stock on 85 hectares of land.\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\t                             Maximum daily     Average daily      Total annual\n',
 '\t                             kg/cow     kg     kg/cow     kg     kg/cow      kg\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\tAmmonia\n',
 '\t   Housing facility          0.077      15     0.023       5       8.2      1647\n',
 '\t   Manure storage            0.316      63     0.056      11      20.3      4064\n',
 '\t   Field application         1.326     265     0.069      14      25.3      5055\n',
 '\t   Grazing                   0.142      28     0.035       7      12.8      2553\n',
 '\t      Total farm             1.552     310     0.182      36      66.6     13319\n',
 '\n',
 '\tHydrogen Sulfide\n',
 '\t   Housing facility          0.000       0     0.000       0       0.1        11\n',
 '\t   Manure storage            0.007       1     0.002       0       0.6       111\n',
 '\t   Field application         0.038       8     0.002       0       0.7       141\n',
 '\t   Grazing                   0.000       0     0.000       0       0.0         1\n',
 '\t      Total farm             0.041       8     0.004       1       1.3       263\n',
 '\n',
 '\tOzone Forming VOC\n',
 '\t   Silo face                 0.000       0     0.000       0       0.0         7\n',
 '\t   Silage feeding            0.004       1     0.002       0       0.6       129\n',
 '\t   Housing manure            0.001       0     0.000       0       0.2        32\n',
 '\t   Manure storage            0.019       4     0.003       1       1.2       238\n',
 '\t   Field / grazing           0.056      11     0.004       1       1.6       328\n',
 '\t      Total farm             0.065      13     0.010       2       3.7       734\n',
 '\n',
 '\tMethane\n',
 '\t   Animal                    0.525     105     0.453      91     165.2     33035\n',
 '\t   Housing manure            0.100      20     0.028       6      10.1      2027\n',
 '\t   Manure storage            0.198      40     0.061      12      22.2      4440\n',
 '\t   Field application         0.017       3     0.004       1       1.6       311\n',
 '\t      Total farm             0.683     137     0.545     109     199.1     39813\n',
 '\n',
 '\tNitrous Oxide\n',
 '\t   Animal                    0.001       0     0.000       0       0.2        36\n',
 '\t   Housing manure            0.007       1     0.002       0       0.6       119\n',
 '\t   Farmland                  0.021       4     0.004       1       1.4       288\n',
 '\t   Indirect sources          0.004       1     0.004       1       1.5       302\n',
 '\t      Total farm             0.027       5     0.010       2       3.7       744\n',
 '\n',
 '\tBiogenic Carbon Dioxide\n',
 '\t   Housing facility         15.766    3153     7.435    1487    2713.8    542758\n',
 '\t   Manure storage            1.453     291     0.440      88     160.4     32086\n',
 '\t   Grazing                  11.593    2319     6.615    1323    2414.4    482885\n',
 '\t   Net land and feed           ---     ---   -20.644   -4129   -7534.9  -1506981\n',
 '\t      Total farm               ---     ---    -6.154   -1231   -2246.3   -449254\n',
 '\n',
 '\tAnthropogenic Carbon Dioxide   ---     ---     1.496     299     546.1    109229\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\n',
 '\n',
 '\tEnvironmental footprints of water, nitrogen, energy and carbon for a dairy farm\n',
 '\twith 200 cows and 129 other stock on 85 hectares of land.\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\t                                               Unit          Mean          SD\n',
 '\t_________________________________________________________________________________\n',
 '\n',
 '\tWater Use\n',
 '\t   Feed production, rainfall                    Mg          596423       37417\n',
 '\t   Evapotranspiration                           Mg          564142       33732\n',
 '\t   Drinking                                     Mg            6033          34\n',
 '\t   Animal cooling and dust control              Mg              52          34\n',
 '\t   Parlor and equipment cleaning                Mg            1825           0\n',
 '\t   Production of purchased feed and inputs      Mg          478540       36824\n',
 '\t   Not allocated to milk production             Mg          -44458        3393\n',
 '\t      Green water footprint                 kg/kg FPCM         639          11\n',
 '\t      Blue water footprint                  kg/kg FPCM       223.5        17.0\n',
 '\n',
 '\tReactive Nitrogen Loss\n',
 '\t   Ammonia emission                             kg           10953         695\n',
 '\t   Nitrate leaching and runoff                  kg           11649        2415\n',
 '\t   De/nitrification emissions                   kg            4001         462\n',
 '\t   Fuel combustion emissions                    kg              82           1\n',
 '\t   Production of resource inputs                kg            3010          27\n',
 '\t   Not allocated to milk production             kg           -2877         240\n',
 '\t      Reactive nitrogen footprint            g/kg FPCM       13.56        1.21\n',
 '\n',
 '\tEnergy Use\n',
 '\t   Feed production                              MJ          117592        2857\n',
 '\t   Animal feeding                               MJ          104097        3164\n',
 '\t   Manure handling                              MJ           48747         520\n',
 '\t   Milking and milk cooling                     MJ          389252         678\n',
 '\t   Animal housing ventilation and lighting      MJ           70927           0\n',
 '\t   Production of resource inputs                MJ         4082577       95273\n',
 '\t   Not allocated to milk production             MJ         -465426        8939\n',
 '\t      Energy footprint                       MJ/kg FPCM       2.20        0.04\n',
 '\n',
 '\tGreenhouse Gas Emissions (CO2e)\n',
 '\t   Animal emissions                             kg          934537        3234\n',
 '\t   Manure emissions                             kg          221202       16093\n',
 '\t   Direct and indirect land emissions           kg          156165       14333\n',
 '\t   Net biogenic carbon dioxide emissions        kg         -449254           0\n',
 '\t   Anthropogenic carbon dioxide emissions       kg          109229         374\n',
 '\t   Production of resource inputs                kg          466848        8311\n',
 '\t   Not allocated to milk production             kg         -186851        2605\n',
 '\t      Carbon footprint without biogenic CO2  kg/kg FPCM      0.860        0.01\n',
 '\t      Carbon footprint with biogenic CO2     kg/kg FPCM      0.654        0.01\n',
 '\t_________________________________________________________________________________\n',
 '\tFPCM is fat and protein corrected milk (4.0% fat and 3.3% protein)']

### HERE THIS IS A WAY TO SEPARATE OUT EACH TABLE...

- NEED TO NOTE THAT IT Seems that in index 1 for each group of 3 that by adding 2 we can get all of the table values...

In [187]:
## Need to determine at what indexes the table breaks... then we can fully split everything up
# # for this we will be looking specifically for the -----------------------
f = open("IFSM_srm1.txt", 'r')
# get all lines
lines = f.readlines()

# convert the list to a numpy array
test_array = np.array(lines)
 
# find the indices of the value 3 in the array
res_array1 = np.where(test_array == '\t__________________________________________________________________________________\n' )
res_array2 = np.where(test_array =='\t_________________________________________________________________________________\n')
# convert the numpy array back to a list
print(len(res_array1[0]))
print(len(res_array2[0]))

table_sep_idxs = list(res_array1[0]) + list(res_array2[0])
print(table_sep_idxs)
table_sep_idx_sorted = sorted(table_sep_idxs)
# print(res_array[0])
# print(test_array[res_array[0]])

## now take this list and create groups of three...
### groups of three because that is how the tables are formatted essentially with these three lines
table_idxs = []
counter = 0
# get value and the couter
curr_list = 0
for count, val in enumerate(table_sep_idx_sorted , start = counter):
    
    if count == 0:
        # create new list
        table_idxs.append([val])
        print("count:", count, "curr_list:",curr_list)
    elif count%3 == 0:
        # change current_list num
        curr_list = len(table_idxs)
        # create new list
        table_idxs.append([val])
        print("count:", count, "curr_list:",curr_list)
    else:
        # add to current list
        table_idxs[curr_list].append(val)
        print("count:", count, "curr_list:",curr_list)
table_idxs

9
9
[4, 9, 15, 21, 24, 41, 44, 78, 81, 35, 72, 97, 103, 107, 153, 159, 162, 204]
count: 0 curr_list: 0
count: 1 curr_list: 0
count: 2 curr_list: 0
count: 3 curr_list: 1
count: 4 curr_list: 1
count: 5 curr_list: 1
count: 6 curr_list: 2
count: 7 curr_list: 2
count: 8 curr_list: 2
count: 9 curr_list: 3
count: 10 curr_list: 3
count: 11 curr_list: 3
count: 12 curr_list: 4
count: 13 curr_list: 4
count: 14 curr_list: 4
count: 15 curr_list: 5
count: 16 curr_list: 5
count: 17 curr_list: 5

[[4, 9, 15],
 [21, 24, 35],
 [41, 44, 72],
 [78, 81, 97],
 [103, 107, 153],
 [159, 162, 204]]

In [7]:
lines[81:97]

['\t__________________________________________________________________________________\n',
 '\n',
 '\t  Equipment cost                                   $        41976         246\n',
 '\t  Facilities cost                                  $        86883         446\n',
 '\t  Energy cost                                      $        20027         122\n',
 '\t  Labor cost                                       $        67797         285\n',
 '\t  Seed, fertilizer and chemical cost               $        14863           0\n',
 '\t  Net purchased feed and bedding cost              $       279079        9281\n',
 '\t  Animal purchase and livestock expense            $        74625           0\n',
 '\t  Milk hauling and marketing fees                  $        33677          59\n',
 '\t  Property tax                                     $         5979           0\n',
 '\n',
 '\t  Income from milk sales                           $       673539        1173\n',
 '\t  Income from animal sales                         $        53648           0\n',
 '\n',
 '\t  Return to management and unpaid factors          $       102281        9381\n']

In [266]:
lines[109:153]

['\tAmmonia\n',
 '\t   Housing facility          0.077      15     0.023       5       8.2      1647\n',
 '\t   Manure storage            0.316      63     0.056      11      20.3      4064\n',
 '\t   Field application         1.326     265     0.069      14      25.3      5055\n',
 '\t   Grazing                   0.142      28     0.035       7      12.8      2553\n',
 '\t      Total farm             1.552     310     0.182      36      66.6     13319\n',
 '\n',
 '\tHydrogen Sulfide\n',
 '\t   Housing facility          0.000       0     0.000       0       0.1        11\n',
 '\t   Manure storage            0.007       1     0.002       0       0.6       111\n',
 '\t   Field application         0.038       8     0.002       0       0.7       141\n',
 '\t   Grazing                   0.000       0     0.000       0       0.0         1\n',
 '\t      Total farm             0.041       8     0.004       1       1.3       263\n',
 '\n',
 '\tOzone Forming VOC\n',
 '\t   Silo face                 0.000       0     0.000       0       0.0         7\n',
 '\t   Silage feeding            0.004       1     0.002       0       0.6       129\n',
 '\t   Housing manure            0.001       0     0.000       0       0.2        32\n',
 '\t   Manure storage            0.019       4     0.003       1       1.2       238\n',
 '\t   Field / grazing           0.056      11     0.004       1       1.6       328\n',
 '\t      Total farm             0.065      13     0.010       2       3.7       734\n',
 '\n',
 '\tMethane\n',
 '\t   Animal                    0.525     105     0.453      91     165.2     33035\n',
 '\t   Housing manure            0.100      20     0.028       6      10.1      2027\n',
 '\t   Manure storage            0.198      40     0.061      12      22.2      4440\n',
 '\t   Field application         0.017       3     0.004       1       1.6       311\n',
 '\t      Total farm             0.683     137     0.545     109     199.1     39813\n',
 '\n',
 '\tNitrous Oxide\n',
 '\t   Animal                    0.001       0     0.000       0       0.2        36\n',
 '\t   Housing manure            0.007       1     0.002       0       0.6       119\n',
 '\t   Farmland                  0.021       4     0.004       1       1.4       288\n',
 '\t   Indirect sources          0.004       1     0.004       1       1.5       302\n',
 '\t      Total farm             0.027       5     0.010       2       3.7       744\n',
 '\n',
 '\tBiogenic Carbon Dioxide\n',
 '\t   Housing facility         15.766    3153     7.435    1487    2713.8    542758\n',
 '\t   Manure storage            1.453     291     0.440      88     160.4     32086\n',
 '\t   Grazing                  11.593    2319     6.615    1323    2414.4    482885\n',
 '\t   Net land and feed           ---     ---   -20.644   -4129   -7534.9  -1506981\n',
 '\t      Total farm               ---     ---    -6.154   -1231   -2246.3   -449254\n',
 '\n',
 '\tAnthropogenic Carbon Dioxide   ---     ---     1.496     299     546.1    109229\n']

In [8]:
string = '\t   Net land and feed           ---     ---   -20.644   -4129   -7534.9  -1506981\n'
string.split("  ")

['\t',
 ' Net land and feed',
 '',
 '',
 '',
 '',
 ' ---',
 '',
 ' ---',
 ' -20.644',
 ' -4129',
 ' -7534.9',
 '-1506981\n']

# For Loop to Extract an Example Table Out And Assign to Dictionary...

In [188]:
# USING FOR LOOP....THIS WORKS FOR THE FIRST TABLE!!!
### ESSENTIALLY COULD USE THIS BUT NEED TO KNOW THE TABLE BREAKS!


f = open("IFSM_srm1.txt", 'r')
# get all lines
lines = f.readlines()


# okay here is example what I am trying to get..
## we set a dictionary to save the data to...
### first element of each list will be the key and rest of the elements will be the elements of a new list set as the value to that key
data_save = {}

str_test = lines[11:15] # should be 9 but doesnt work due to spaces and such so +2 to get 11 gets actual data....

for lne in str_test:
    # first we do a replacement of the tab and newline characters
    a = lne.replace('\t',"").replace('\n',"")

    # after this point we need to split by two spaces so that we still have any row headers by can also split up everything 
    b = a.split('  ') 

    # using list comprehension we get rid of all empty strings
    c =[x for x in b if len(x)>0 ]

    # Then we make sure that the first element is a string and all other values are converted to be floats
    d = [float(c[val]) if val >0  else c[val] for val in range(len(c))]

    # now in this last part we have a list with numerical data and a row header... this row header will be set as a key in the dictionary
    ## then the rest of the list will be set as the value to that key
    data_save[d[0]]=d[1:]

data_save

{'GRASS, 85 ha': [],
 'Cutting 1': [3.92, 15.6, 44.8, 3.69, 16.0, 47.7],
 'Cutting 2': [2.56, 18.6, 42.8, 2.46, 18.8, 44.2],
 'Total': [6.48, 16.8, 44.1, 6.15, 17.4, 46.0]}

# WORKING VERSION FOR FULL TEXTFILE TO DICTIONARY...
### Using Same Structure as Above Test to See if we can Get Everything Separated...


*Missing The Headers and Columns Distinctions*

*Need to Split into separate dictionaries one for each table... then we can save those all as csvs...*



### THERE IS AN ERROR STILL:
**Daily and annual emissions of important gaseous compounds for a dairy farm with
	200 cows and 129 other stock on 85 hectares of land.** <- Missing Data and Also Compltely wrong data for all of this section....>

	* okay everyting is working well the issue is just that we have multiple of same key so then it gets overwritten...
	* solution is to make dictionaries and sub dictionaries...
	* Also need to add more labels so if there is a string followed by long space then need to add that to the front of the next successive string names...
		- will aid  in makling unique items...

- New idea is to essentially create a whole new dictionary each time..??? for each table? This will make more sense I think...

In [189]:
f = open("IFSM_srm1.txt", 'r')
# get all lines
lines = f.readlines()

# function to detemrine if string is actually a float...
def isfloat(num):
    try:
        float(num)
        return True
    except ValueError:
        return False

# okay here is example what I am trying to get..
## we set a dictionary to save the data to...
### first element of each list will be the key and rest of the elements will be the elements of a new list set as the value to that key
data_save = {}

## So we will be going through all of the table indexes..
print(table_idxs)
for idx_trio in table_idxs:
    str_test = lines[idx_trio[1]+2:idx_trio[2]]
    # #print(idx_trio)
    print(str_test)
    for lne in str_test:
        
        # first we do a replacement of the tab and newline characters
        a = lne.replace('\t',"").replace('\n',"")
        # after this point we need to split by two spaces so that we still have any row headers by can also split up everything 
        b = a.split('  ') 

        # using list comprehension we get rid of all empty strings
        c =[x for x in b if len(x)>0 ]

        #print("list of data", c)
        # ADDED CONDITION: IF THERE IS JUST A A BLANK LINE WHICH AT THIS POINT WOULD BE [''] then dont add it to the dictionary....
        if len(c) > 0:
            # Then we make sure that the first element is a string and all other values are converted to be floats
            # d = [c[val] if val == 0 else float(c[val]) if isfloat(c[val])==False else c[val] for val in range(len(c))]

            ## if it is index 0 then keep it as is... 
            ## then after index 0 we will then check to see if value is a float or not...
            d = []
            for val in range(len(c)):
                if val == 0:
                    d.append(c[val])
                elif isfloat(c[val]):
                    d.append(float(c[val]))

                else:
                    d.append(c[val])




            # now in this last part we have a list with numerical data and a row header... this row header will be set as a key in the dictionary
            ## then the rest of the list will be set as the value to that key
            data_save[d[0]]=d[1:]

data_save

[[4, 9, 15], [21, 24, 35], [41, 44, 72], [78, 81, 97], [103, 107, 153], [159, 162, 204]]
['\tGRASS, 85 ha\n', '\t  Cutting 1       3.92       15.6       44.8          3.69       16.0       47.7\n', '\t  Cutting 2       2.56       18.6       42.8          2.46       18.8       44.2\n', '\t    Total         6.48       16.8       44.1          6.15       17.4       46.0\n']
['\t  High-quality silage production                 t DM         150          19\n', '\t  Grazed forage consumed                         t DM         320          42\n', '\t  Forage purchased                               t DM         641          53\n', '\t  Grain purchased                                t DM         554           6\n', '\t  Soybean meal, 44% purchased                    t DM           6           4\n', '\t  User defined feed purchased                    t DM          28           3\n', '\t  Mineral and vitamin mix purchased              t DM          10           0\n', '\t  Milk production                               L/cow        8419          15\n', '\t  Fat and protein corrected milk production    kg/cow        9890          17\n']
['\t  Nitrogen imported to farm                     kg/ha       479.2        17.5\n', '\t  Nitrogen exported from farm                   kg/ha       124.1         0.0\n', '\t  Nitrogen lost by volatilization               kg/ha       128.9         8.2\n', '\t  Nitrogen lost by leaching                     kg/ha       136.8        28.4\n', '\t  Nitrogen lost by de/nitrification             kg/ha        47.6         5.4\n', '\t  Nitrogen lost by runoff                       kg/ha         0.3         0.2\n', '\t  Nitrogen concentration in leachate             ppm          9.3         2.3\n', '\t  Whole-farm excess nitrogen                    kg/ha        47.1        29.8\n', '\n', '\t  Phosphorous imported to farm                  kg/ha        50.8         1.7\n', '\t  Phosphorous exported from farm                kg/ha        17.5         0.0\n', '\t  Phosphorous available on farm                 kg/ha        49.2         4.2\n', '\t  Phosphorous loss in runoff and leachate       kg/ha         1.1         0.7\n', '\t  Whole-farm excess phosphorus                  kg/ha        32.3         1.7\n', '\n', '\t  Potassium imported to farm                    kg/ha       187.4        10.1\n', '\t  Potassium exported from farm                  kg/ha        25.6         0.0\n', '\t  Potassium available on farm                   kg/ha       314.8        27.2\n', '\t  Potassium loss through runoff                 kg/ha        15.7         1.4\n', '\t  Whole-farm excess potassium                   kg/ha       146.1        10.4\n', '\n', '\t  Carbon imported to farm                       kg/ha     15031.7       934.7\n', '\t  Carbon exported from farm                     kg/ha      1441.5         0.0\n', '\t  Carbon loss as carbon dioxide                 kg/ha     13237.6       935.9\n', '\t  Carbon loss as methane                        kg/ha       351.3         4.2\n', '\t  Carbon loss through runoff                    kg/ha         1.3         0.8\n']
['\t  Equipment cost                                   $        41976         246\n', '\t  Facilities cost                                  $        86883         446\n', '\t  Energy cost                                      $        20027         122\n', '\t  Labor cost                                       $        67797         285\n', '\t  Seed, fertilizer and chemical cost               $        14863           0\n', '\t  Net purchased feed and bedding cost              $       279079        9281\n', '\t  Animal purchase and livestock expense            $        74625           0\n', '\t  Milk hauling and marketing fees                  $        33677          59\n', '\t  Property tax                                     $         5979           0\n', '\n', '\t  Income from milk sales                           $       673539        1173\n', '\t  Income from animal sales                         $        53648           0\n', '\n', '\t  Return to management and unpaid factors          $       102281        9381\n']
['\tAmmonia\n', '\t   Housing facility          0.077      15     0.023       5       8.2      1647\n', '\t   Manure storage            0.316      63     0.056      11      20.3      4064\n', '\t   Field application         1.326     265     0.069      14      25.3      5055\n', '\t   Grazing                   0.142      28     0.035       7      12.8      2553\n', '\t      Total farm             1.552     310     0.182      36      66.6     13319\n', '\n', '\tHydrogen Sulfide\n', '\t   Housing facility          0.000       0     0.000       0       0.1        11\n', '\t   Manure storage            0.007       1     0.002       0       0.6       111\n', '\t   Field application         0.038       8     0.002       0       0.7       141\n', '\t   Grazing                   0.000       0     0.000       0       0.0         1\n', '\t      Total farm             0.041       8     0.004       1       1.3       263\n', '\n', '\tOzone Forming VOC\n', '\t   Silo face                 0.000       0     0.000       0       0.0         7\n', '\t   Silage feeding            0.004       1     0.002       0       0.6       129\n', '\t   Housing manure            0.001       0     0.000       0       0.2        32\n', '\t   Manure storage            0.019       4     0.003       1       1.2       238\n', '\t   Field / grazing           0.056      11     0.004       1       1.6       328\n', '\t      Total farm             0.065      13     0.010       2       3.7       734\n', '\n', '\tMethane\n', '\t   Animal                    0.525     105     0.453      91     165.2     33035\n', '\t   Housing manure            0.100      20     0.028       6      10.1      2027\n', '\t   Manure storage            0.198      40     0.061      12      22.2      4440\n', '\t   Field application         0.017       3     0.004       1       1.6       311\n', '\t      Total farm             0.683     137     0.545     109     199.1     39813\n', '\n', '\tNitrous Oxide\n', '\t   Animal                    0.001       0     0.000       0       0.2        36\n', '\t   Housing manure            0.007       1     0.002       0       0.6       119\n', '\t   Farmland                  0.021       4     0.004       1       1.4       288\n', '\t   Indirect sources          0.004       1     0.004       1       1.5       302\n', '\t      Total farm             0.027       5     0.010       2       3.7       744\n', '\n', '\tBiogenic Carbon Dioxide\n', '\t   Housing facility         15.766    3153     7.435    1487    2713.8    542758\n', '\t   Manure storage            1.453     291     0.440      88     160.4     32086\n', '\t   Grazing                  11.593    2319     6.615    1323    2414.4    482885\n', '\t   Net land and feed           ---     ---   -20.644   -4129   -7534.9  -1506981\n', '\t      Total farm               ---     ---    -6.154   -1231   -2246.3   -449254\n', '\n', '\tAnthropogenic Carbon Dioxide   ---     ---     1.496     299     546.1    109229\n']
['\tWater Use\n', '\t   Feed production, rainfall                    Mg          596423       37417\n', '\t   Evapotranspiration                           Mg          564142       33732\n', '\t   Drinking                                     Mg            6033          34\n', '\t   Animal cooling and dust control              Mg              52          34\n', '\t   Parlor and equipment cleaning                Mg            1825           0\n', '\t   Production of purchased feed and inputs      Mg          478540       36824\n', '\t   Not allocated to milk production             Mg          -44458        3393\n', '\t      Green water footprint                 kg/kg FPCM         639          11\n', '\t      Blue water footprint                  kg/kg FPCM       223.5        17.0\n', '\n', '\tReactive Nitrogen Loss\n', '\t   Ammonia emission                             kg           10953         695\n', '\t   Nitrate leaching and runoff                  kg           11649        2415\n', '\t   De/nitrification emissions                   kg            4001         462\n', '\t   Fuel combustion emissions                    kg              82           1\n', '\t   Production of resource inputs                kg            3010          27\n', '\t   Not allocated to milk production             kg           -2877         240\n', '\t      Reactive nitrogen footprint            g/kg FPCM       13.56        1.21\n', '\n', '\tEnergy Use\n', '\t   Feed production                              MJ          117592        2857\n', '\t   Animal feeding                               MJ          104097        3164\n', '\t   Manure handling                              MJ           48747         520\n', '\t   Milking and milk cooling                     MJ          389252         678\n', '\t   Animal housing ventilation and lighting      MJ           70927           0\n', '\t   Production of resource inputs                MJ         4082577       95273\n', '\t   Not allocated to milk production             MJ         -465426        8939\n', '\t      Energy footprint                       MJ/kg FPCM       2.20        0.04\n', '\n', '\tGreenhouse Gas Emissions (CO2e)\n', '\t   Animal emissions                             kg          934537        3234\n', '\t   Manure emissions                             kg          221202       16093\n', '\t   Direct and indirect land emissions           kg          156165       14333\n', '\t   Net biogenic carbon dioxide emissions        kg         -449254           0\n', '\t   Anthropogenic carbon dioxide emissions       kg          109229         374\n', '\t   Production of resource inputs                kg          466848        8311\n', '\t   Not allocated to milk production             kg         -186851        2605\n', '\t      Carbon footprint without biogenic CO2  kg/kg FPCM      0.860        0.01\n', '\t      Carbon footprint with biogenic CO2     kg/kg FPCM      0.654        0.01\n']

{'GRASS, 85 ha': [],
 'Cutting 1': [3.92, 15.6, 44.8, 3.69, 16.0, 47.7],
 'Cutting 2': [2.56, 18.6, 42.8, 2.46, 18.8, 44.2],
 'Total': [6.48, 16.8, 44.1, 6.15, 17.4, 46.0],
 'High-quality silage production': [' t DM', 150.0, 19.0],
 'Grazed forage consumed': [' t DM', 320.0, 42.0],
 'Forage purchased': [' t DM', 641.0, 53.0],
 'Grain purchased': ['t DM', 554.0, 6.0],
 'Soybean meal, 44% purchased': ['t DM', 6.0, 4.0],
 'User defined feed purchased': ['t DM', 28.0, 3.0],
 'Mineral and vitamin mix purchased': ['t DM', 10.0, 0.0],
 'Milk production': [' L/cow', 8419.0, 15.0],
 'Fat and protein corrected milk production': ['kg/cow', 9890.0, 17.0],
 'Nitrogen imported to farm': [' kg/ha', 479.2, 17.5],
 'Nitrogen exported from farm': [' kg/ha', 124.1, 0.0],
 'Nitrogen lost by volatilization': [' kg/ha', 128.9, 8.2],
 'Nitrogen lost by leaching': [' kg/ha', 136.8, 28.4],
 'Nitrogen lost by de/nitrification': [' kg/ha', 47.6, 5.4],
 'Nitrogen lost by runoff': [' kg/ha', 0.3, 0.2],
 'Nitrogen concentration in leachate': [' ppm', 9.3, 2.3],
 'Whole-farm excess nitrogen': ['kg/ha', 47.1, 29.8],
 'Phosphorous imported to farm': ['kg/ha', 50.8, 1.7],
 'Phosphorous exported from farm': ['kg/ha', 17.5, 0.0],
 'Phosphorous available on farm': [' kg/ha', 49.2, 4.2],
 'Phosphorous loss in runoff and leachate': [' kg/ha', 1.1, 0.7],
 'Whole-farm excess phosphorus': ['kg/ha', 32.3, 1.7],
 'Potassium imported to farm': ['kg/ha', 187.4, 10.1],
 'Potassium exported from farm': ['kg/ha', 25.6, 0.0],
 'Potassium available on farm': [' kg/ha', 314.8, 27.2],
 'Potassium loss through runoff': [' kg/ha', 15.7, 1.4],
 'Whole-farm excess potassium': [' kg/ha', 146.1, 10.4],
 'Carbon imported to farm': [' kg/ha', 15031.7, 934.7],
 'Carbon exported from farm': [' kg/ha', 1441.5, 0.0],
 'Carbon loss as carbon dioxide': [' kg/ha', 13237.6, 935.9],
 'Carbon loss as methane': ['kg/ha', 351.3, 4.2],
 'Carbon loss through runoff': ['kg/ha', 1.3, 0.8],
 'Equipment cost': [' $', 41976.0, 246.0],
 'Facilities cost': ['$', 86883.0, 446.0],
 'Energy cost': ['$', 20027.0, 122.0],
 'Labor cost': [' $', 67797.0, 285.0],
 'Seed, fertilizer and chemical cost': [' $', 14863.0, 0.0],
 'Net purchased feed and bedding cost': ['$', 279079.0, 9281.0],
 'Animal purchase and livestock expense': ['$', 74625.0, 0.0],
 'Milk hauling and marketing fees': ['$', 33677.0, 59.0],
 'Property tax': [' $', 5979.0, 0.0],
 'Income from milk sales': [' $', 673539.0, 1173.0],
 'Income from animal sales': [' $', 53648.0, 0.0],
 'Return to management and unpaid factors': ['$', 102281.0, 9381.0],
 'Ammonia': [],
 ' Housing facility': [15.766, 3153.0, 7.435, 1487.0, 2713.8, 542758.0],
 ' Manure storage': [1.453, 291.0, 0.44, 88.0, 160.4, 32086.0],
 ' Field application': [0.017, 3.0, 0.004, 1.0, 1.6, 311.0],
 ' Grazing': [11.593, 2319.0, 6.615, 1323.0, 2414.4, 482885.0],
 'Total farm': [' ---', ' ---', -6.154, -1231.0, -2246.3, -449254.0],
 'Hydrogen Sulfide': [],
 'Ozone Forming VOC': [],
 ' Silo face': [0.0, 0.0, 0.0, 0.0, 0.0, 7.0],
 ' Silage feeding': [0.004, 1.0, 0.002, 0.0, 0.6, 129.0],
 ' Housing manure': [0.007, 1.0, 0.002, 0.0, 0.6, 119.0],
 ' Field / grazing': [0.056, 11.0, 0.004, 1.0, 1.6, 328.0],
 'Methane': [],
 ' Animal': [0.001, 0.0, 0.0, 0.0, 0.2, 36.0],
 'Nitrous Oxide': [],
 ' Farmland': [0.021, 4.0, 0.004, 1.0, 1.4, 288.0],
 ' Indirect sources': [0.004, 1.0, 0.004, 1.0, 1.5, 302.0],
 'Biogenic Carbon Dioxide': [],
 ' Net land and feed': [' ---', ' ---', -20.644, -4129.0, -7534.9, -1506981.0],
 'Anthropogenic Carbon Dioxide': [' ---',
  ' ---',
  1.496,
  299.0,
  546.1,
  109229.0],
 'Water Use': [],
 ' Feed production, rainfall': ['Mg', 596423.0, 37417.0],
 ' Evapotranspiration': [' Mg', 564142.0, 33732.0],
 ' Drinking': [' Mg', 6033.0, 34.0],
 ' Animal cooling and dust control': ['Mg', 52.0, 34.0],
 ' Parlor and equipment cleaning': ['Mg', 1825.0, 0.0],
 ' Production of purchased feed and inputs': ['Mg', 478540.0, 36824.0],
 ' Not allocated to milk production': [' kg', -186851.0, 2605.0],
 'Green water footprint': [' kg/kg FPCM', 639.0, 11.0],
 'Blue water footprint': ['kg/kg FPCM', 223.5, 17.0],
 'Reactive Nitrogen Loss': [],
 ' Ammonia emission': [' kg', 10953.0, 695.0],
 ' Nitrate leaching and runoff': ['kg', 11649.0, 2415.0],
 ' De/nitrification emissions': [' kg', 4001.0, 462.0],
 ' Fuel combustion emissions': ['kg', 82.0, 1.0],
 ' Production of resource inputs': ['kg', 466848.0, 8311.0],
 'Reactive nitrogen footprint': ['g/kg FPCM', 13.56, 1.21],
 'Energy Use': [],
 ' Feed production': ['MJ', 117592.0, 2857.0],
 ' Animal feeding': [' MJ', 104097.0, 3164.0],
 ' Manure handling': ['MJ', 48747.0, 520.0],
 ' Milking and milk cooling': [' MJ', 389252.0, 678.0],
 ' Animal housing ventilation and lighting': ['MJ', 70927.0, 0.0],
 'Energy footprint': [' MJ/kg FPCM', 2.2, 0.04],
 'Greenhouse Gas Emissions (CO2e)': [],
 ' Animal emissions': [' kg', 934537.0, 3234.0],
 ' Manure emissions': [' kg', 221202.0, 16093.0],
 ' Direct and indirect land emissions': [' kg', 156165.0, 14333.0],
 ' Net biogenic carbon dioxide emissions': ['kg', -449254.0, 0.0],
 ' Anthropogenic carbon dioxide emissions': [' kg', 109229.0, 374.0],
 'Carbon footprint without biogenic CO2': ['kg/kg FPCM', 0.86, 0.01],
 'Carbon footprint with biogenic CO2': [' kg/kg FPCM', 0.654, 0.01]}

In [25]:
len(table_idxs)

6

In [226]:
## Created a Function that can be run... what this will do is it will take the table index range
### for what we are looking for and then get that table
### However, for specific tables there are specific rules

### each input dictionary will have the defined units already. if table has a units or 
#### Units then overwrite it... as it will be fully filled out
### In addition after the units we will only add the keys that are listed in the new table dictionary 
#### so we will drop some 

def add_data_dict(text_file,table_idx_num):
    """
    Inputs are the text_file where the data originates, and the table_dict, which is the 
    dictionary that we will be saving these values to that has certain stipulations
    """
    # assign the index trio
    idx_trio = table_idxs[table_idx_num]

    f = open(text_file, 'r')
    # get all lines
    lines = f.readlines()

    # function to detemrine if string is actually a float...
    def isfloat(num):
        try:
            float(num)
            return True
        except ValueError:
            return False

    # okay here is example what I am trying to get..
    ## we set a dictionary to save the data to...
    ### first element of each list will be the key and rest of the elements will be the elements of a new list set as the value to that key
    data_save = {}
    ## So we will be using the table indicies
    # print(idx_trio)
    str_test = lines[idx_trio[1]+2:idx_trio[2]]
    # #print(idx_trio)
    #print(str_test)
    for lne in str_test:
        # first we do a replacement of the tab and newline characters
        a = lne.replace('\t',"").replace('\n',"")
        # after this point we need to split by two spaces so that we still have any row headers by can also split up everything 
        b = a.split('  ') 

        # using list comprehension we get rid of all empty strings
        c =[x for x in b if len(x)>0 ]

        #print("list of data", c)
        # ADDED CONDITION: IF THERE IS JUST A A BLANK LINE WHICH AT THIS POINT WOULD BE [''] then dont add it to the dictionary....
        if len(c) > 0:
            # Then we make sure that the first element is a string and all other values are converted to be floats
            # d = [c[val] if val == 0 else float(c[val]) if isfloat(c[val])==False else c[val] for val in range(len(c))]

            ## if it is index 0 then keep it as is... 
            ## then after index 0 we will then check to see if value is a float or not...
            d = []
            for val in range(len(c)):
                if val == 0:
                    d.append(c[val])
                elif isfloat(c[val]):
                    d.append(float(c[val]))

                else:
                    d.append(c[val])




            # now in this last part we have a list with numerical data and a row header... this row header will be set as a key in the dictionary
            ## then the rest of the list will be set as the value to that key
            # print(d[0])
            # print(d[1:])
            data_save[d[0]]=d[1:]
            # essentially we will check to see if the key already exists in the table_dict.keys()
            ## What we want to first do is if there is no units key then we add that in
    ## if there is a units key then we overwrite it
    ## However we want to make sure that we are only adding the other keys that are listed in the table_dict keys...
    # if "units" not in table_dict.keys():
    #     data_save['units']=d[1:]
    
            ## check to see if the dictionary is equal to a list
            ## if it is we will need to make a sub dictionary
    # Iterate through the dictionary and add the  keys that have the blank...[] to start of the keys that are "beneath them"
    ## created a copy of the original list of keys
    lst_keys = list(data_save.keys())
    ## create a value that wills store the current key that needs to be added to start of names
    val_k =''
    for k in lst_keys:
        ## check if the current value of k is an empty list...
        ### right not wont consider case of first table with the empty list GRASS
        if len(data_save[k]) ==0:
            ## assign the new value
            val_k = k
            ## after assigning the value of k, delete the instance in the dictionary
            ### this is done before start of next loop...
            data_save.pop(k)
        elif data_save[k] !=[] and len(val_k)>0:
            ## so if the value of the current key is noty an empty list then we can change the 
            ### name of the key and then also delete the old key
            data_save[val_k+'_'+k] = data_save[k]
            ## delete old key
            data_save.pop(k)




# # CLOSE TO WORKING!  
#     empty_list = []
#     for k in data_save:
#         if data_save[k] == [] and k != 'GRASS, 85 ha':
#             empty_list.append((k, list(data_save.keys()).index(k),len(data_save[k])))

#     # empty_lst = [(k, list(data_save.keys()).index(k)) for k in data_save if data_save[k] == []]
#     # print('start list fix',empty_list)
#     # Created list of all keys
#     k_list = list(data_save.keys())
#     # so if there is indeed a situation in which there are empty lists assigned as values to a key
#     ## then will proceed within this conditional, if not then will return dictionary
#     if len(empty_list) > 0:
#         # then what will happen is that each key will be iterated over and the values within the index range they correspond to will then be mutatetd
#         for k in range(len(empty_list)):
#             print((empty_list[k][0]))
#             ## create the ranges
#             r1 = empty_list[k][1]
#             if k< len(empty_list) -1:
#                 r2 = empty_list[k+1][1]
#             else:
#                 r2 = empty_list[k][2]-1
#             for idx in k_list[r1+1:r2]:
#                 # print(empty_list[k][0])
#                 # print(idx)
#                 data_save[empty_list[k][0]+'_'+idx] = data_save[idx]
#                 data_save.pop(idx)
#         data_save.pop(empty_list[k][0])
#     print(data_save.keys())


# ### Working version...
#     if data_save[list(data_save.keys())[0]] == []:
#         # if this is the case then what will happen is that for each entry to the beginning there will be this added...
#         var_k = list(data_save.keys())[0]
#         # delete the starting key from the list of keys
#         data_save.pop(var_k)
#         # assign the current keys list to a variable
#         k_list = list(data_save.keys())
#         print(k_list)
#         print(var_k)
#         # for loop to interate through each key and essentailly rename by save key value and makeng new key
#         ## and deleting the old key
#         for k in k_list:
#             data_save[var_k+'_'+k] = data_save[k]
#             data_save.pop(k)

    return data_save

In [151]:
## HOW TO ADD STRING TO THE BEGIING OF ANOTHER STRING?
d = {'a':[],'b':[1,23,41,213,234],'cab':[1231],'cadfe':[23]}
### save the as a variable
var = list(d.keys())[0]
### delete from the dictionary
d.pop('a')

### get the original list of keys
k_list = list(d.keys())

### add variable to the start of each key
for k in k_list:
    d[var+k]= d[k] 
    d.pop(k)
d

{'ab': [1, 23, 41, 213, 234], 'acab': [1231], 'acadfe': [23]}

In [22]:
dict = {'a':1,'3':23,"d":21,"asdfv":'231',"wefd2":123}
print(dict[list(dict.keys())[0]])

1

In [227]:
## Table 1 [4,9,15], aka 
# Average crop yields and nutritive contents over a 25 year analysis of a 85 ha dairy farm.
# table1 = { 'Units': }

table1 = add_data_dict("IFSM_srm1.txt", 0)
table1['Units'] = ['Preharvest t DM/ha','Prehavest Crude Protein','Preharvest NDF','Postharvest t DM/ha','Posthavest Crude Protein','Postharvest NDF']
## Unit Fix
print(table1)
## Table 2 [21,24,35], aka
# Annual feed production and use for a 25 year analysis of a dairy farm 
# with 200 cows and 129 other stock on 85 hectares of land.

table2 = {}
table2 = add_data_dict("IFSM_srm1.txt", 1)
print(table2)
## Table 3 [41,44,72], aka
# 	Nutrients available, used, and lost to the environment for a 25 year analysis of
#	a farm with 200 cows and 129 other stock on 85 hectares of land.

table3 = {}
table3 = add_data_dict("IFSM_srm1.txt", 2)
print(table3)
## Table 4 [78, 81, 97] aka
# Annual production costs and return to management for a 25 year analysis of a 
#	farm with 200 cows and 129 other stock on 85 hectares of land.

table4 ={}
table4 = add_data_dict("IFSM_srm1.txt", 3)
print(table4)
## Table 5
# Daily and annual emissions of important gaseous compounds for a dairy farm with
# 200 cows and 129 other stock on 85 hectares of land. 
table5 ={}
table5 = add_data_dict("IFSM_srm1.txt", 4)
print(table5)
## Table 6 - Environmental Footprints
# 	Environmental footprints of water, nitrogen, energy and carbon for a dairy farm
#	with 200 cows and 129 other stock on 85 hectares of land.

table6 ={}
table6 = add_data_dict("IFSM_srm1.txt", 5)
print(table6)

{'GRASS, 85 ha_Cutting 1': [3.92, 15.6, 44.8, 3.69, 16.0, 47.7], 'GRASS, 85 ha_Cutting 2': [2.56, 18.6, 42.8, 2.46, 18.8, 44.2], 'GRASS, 85 ha_Total': [6.48, 16.8, 44.1, 6.15, 17.4, 46.0], 'Units': ['Preharvest t DM/ha', 'Prehavest Crude Protein', 'Preharvest NDF', 'Postharvest t DM/ha', 'Posthavest Crude Protein', 'Postharvest NDF']}
{'High-quality silage production': [' t DM', 150.0, 19.0], 'Grazed forage consumed': [' t DM', 320.0, 42.0], 'Forage purchased': [' t DM', 641.0, 53.0], 'Grain purchased': ['t DM', 554.0, 6.0], 'Soybean meal, 44% purchased': ['t DM', 6.0, 4.0], 'User defined feed purchased': ['t DM', 28.0, 3.0], 'Mineral and vitamin mix purchased': ['t DM', 10.0, 0.0], 'Milk production': [' L/cow', 8419.0, 15.0], 'Fat and protein corrected milk production': ['kg/cow', 9890.0, 17.0]}
{'Nitrogen imported to farm': [' kg/ha', 479.2, 17.5], 'Nitrogen exported from farm': [' kg/ha', 124.1, 0.0], 'Nitrogen lost by volatilization': [' kg/ha', 128.9, 8.2], 'Nitrogen lost by leaching': [' kg/ha', 136.8, 28.4], 'Nitrogen lost by de/nitrification': [' kg/ha', 47.6, 5.4], 'Nitrogen lost by runoff': [' kg/ha', 0.3, 0.2], 'Nitrogen concentration in leachate': [' ppm', 9.3, 2.3], 'Whole-farm excess nitrogen': ['kg/ha', 47.1, 29.8], 'Phosphorous imported to farm': ['kg/ha', 50.8, 1.7], 'Phosphorous exported from farm': ['kg/ha', 17.5, 0.0], 'Phosphorous available on farm': [' kg/ha', 49.2, 4.2], 'Phosphorous loss in runoff and leachate': [' kg/ha', 1.1, 0.7], 'Whole-farm excess phosphorus': ['kg/ha', 32.3, 1.7], 'Potassium imported to farm': ['kg/ha', 187.4, 10.1], 'Potassium exported from farm': ['kg/ha', 25.6, 0.0], 'Potassium available on farm': [' kg/ha', 314.8, 27.2], 'Potassium loss through runoff': [' kg/ha', 15.7, 1.4], 'Whole-farm excess potassium': [' kg/ha', 146.1, 10.4], 'Carbon imported to farm': [' kg/ha', 15031.7, 934.7], 'Carbon exported from farm': [' kg/ha', 1441.5, 0.0], 'Carbon loss as carbon dioxide': [' kg/ha', 13237.6, 935.9], 'Carbon loss as methane': ['kg/ha', 351.3, 4.2], 'Carbon loss through runoff': ['kg/ha', 1.3, 0.8]}
{'Equipment cost': [' $', 41976.0, 246.0], 'Facilities cost': ['$', 86883.0, 446.0], 'Energy cost': ['$', 20027.0, 122.0], 'Labor cost': [' $', 67797.0, 285.0], 'Seed, fertilizer and chemical cost': [' $', 14863.0, 0.0], 'Net purchased feed and bedding cost': ['$', 279079.0, 9281.0], 'Animal purchase and livestock expense': ['$', 74625.0, 0.0], 'Milk hauling and marketing fees': ['$', 33677.0, 59.0], 'Property tax': [' $', 5979.0, 0.0], 'Income from milk sales': [' $', 673539.0, 1173.0], 'Income from animal sales': [' $', 53648.0, 0.0], 'Return to management and unpaid factors': ['$', 102281.0, 9381.0]}
{'Ammonia_ Housing facility': [15.766, 3153.0, 7.435, 1487.0, 2713.8, 542758.0], 'Ammonia_ Manure storage': [1.453, 291.0, 0.44, 88.0, 160.4, 32086.0], 'Ammonia_ Field application': [0.017, 3.0, 0.004, 1.0, 1.6, 311.0], 'Ammonia_ Grazing': [11.593, 2319.0, 6.615, 1323.0, 2414.4, 482885.0], 'Ammonia_Total farm': [' ---', ' ---', -6.154, -1231.0, -2246.3, -449254.0], 'Ozone Forming VOC_ Silo face': [0.0, 0.0, 0.0, 0.0, 0.0, 7.0], 'Ozone Forming VOC_ Silage feeding': [0.004, 1.0, 0.002, 0.0, 0.6, 129.0], 'Ozone Forming VOC_ Housing manure': [0.007, 1.0, 0.002, 0.0, 0.6, 119.0], 'Ozone Forming VOC_ Field / grazing': [0.056, 11.0, 0.004, 1.0, 1.6, 328.0], 'Methane_ Animal': [0.001, 0.0, 0.0, 0.0, 0.2, 36.0], 'Nitrous Oxide_ Farmland': [0.021, 4.0, 0.004, 1.0, 1.4, 288.0], 'Nitrous Oxide_ Indirect sources': [0.004, 1.0, 0.004, 1.0, 1.5, 302.0], 'Biogenic Carbon Dioxide_ Net land and feed': [' ---', ' ---', -20.644, -4129.0, -7534.9, -1506981.0], 'Biogenic Carbon Dioxide_Anthropogenic Carbon Dioxide': [' ---', ' ---', 1.496, 299.0, 546.1, 109229.0]}
{'Water Use_ Feed production, rainfall': ['Mg', 596423.0, 37417.0], 'Water Use_ Evapotranspiration': [' Mg', 564142.0, 33732.0], 'Water Use_ Drinking': [' Mg', 6033.0, 34.0], 'Water Use_ Animal cooling and dust control': ['Mg', 52.0, 34.0], 'Water Use_ Parlor and equipment cleaning': ['Mg', 1825.0, 0.0], 'Water Use_ Production of purchased feed and inputs': ['Mg', 478540.0, 36824.0], 'Water Use_ Not allocated to milk production': [' kg', -186851.0, 2605.0], 'Water Use_Green water footprint': [' kg/kg FPCM', 639.0, 11.0], 'Water Use_Blue water footprint': ['kg/kg FPCM', 223.5, 17.0], 'Reactive Nitrogen Loss_ Ammonia emission': [' kg', 10953.0, 695.0], 'Reactive Nitrogen Loss_ Nitrate leaching and runoff': ['kg', 11649.0, 2415.0], 'Reactive Nitrogen Loss_ De/nitrification emissions': [' kg', 4001.0, 462.0], 'Reactive Nitrogen Loss_ Fuel combustion emissions': ['kg', 82.0, 1.0], 'Reactive Nitrogen Loss_ Production of resource inputs': ['kg', 466848.0, 8311.0], 'Reactive Nitrogen Loss_Reactive nitrogen footprint': ['g/kg FPCM', 13.56, 1.21], 'Energy Use_ Feed production': ['MJ', 117592.0, 2857.0], 'Energy Use_ Animal feeding': [' MJ', 104097.0, 3164.0], 'Energy Use_ Manure handling': ['MJ', 48747.0, 520.0], 'Energy Use_ Milking and milk cooling': [' MJ', 389252.0, 678.0], 'Energy Use_ Animal housing ventilation and lighting': ['MJ', 70927.0, 0.0], 'Energy Use_Energy footprint': [' MJ/kg FPCM', 2.2, 0.04], 'Greenhouse Gas Emissions (CO2e)_ Animal emissions': [' kg', 934537.0, 3234.0], 'Greenhouse Gas Emissions (CO2e)_ Manure emissions': [' kg', 221202.0, 16093.0], 'Greenhouse Gas Emissions (CO2e)_ Direct and indirect land emissions': [' kg', 156165.0, 14333.0], 'Greenhouse Gas Emissions (CO2e)_ Net biogenic carbon dioxide emissions': ['kg', -449254.0, 0.0], 'Greenhouse Gas Emissions (CO2e)_ Anthropogenic carbon dioxide emissions': [' kg', 109229.0, 374.0], 'Greenhouse Gas Emissions (CO2e)_Carbon footprint without biogenic CO2': ['kg/kg FPCM', 0.86, 0.01], 'Greenhouse Gas Emissions (CO2e)_Carbon footprint with biogenic CO2': [' kg/kg FPCM', 0.654, 0.01]}

## Refine and Combine Tables

#### Currently we now have 6 separate tables. Now we will essentailly do the process again focussing on each such that we have the correct format in order to create some really nice tables that can be converted into something that is usuable by the API


#### We have 6 tables but need to consider the mass and energy flows. As such we are going to make the following assumptions:

- ommit the first table as it is in t DM/ha?
    - we could multiply by number of hectares and then get more information on the yield and crude protein and NDF... However a little confused how this would directly factor into our flow with respect to nitrate and phosphate runoff or overall stuff...

- need to perform computations to get the amounts relative to cows by number of cows to get the volume or mass value...

- In the end there should be a single spreadsheet that has everyting in mass or energy or volume metrics...

- Should also state whether or not it is a reference flow


columns of product name, product type, product input/output, units, the amount, how much of a product is associated with a process

###  Table 1 - Refine into an easily usable table...

In [228]:
## Step 1 we will create a pandas dataframe
df_1 = pd.DataFrame(table1)
df_1

,"GRASS, 85 ha_Cutting 1","GRASS, 85 ha_Cutting 2","GRASS, 85 ha_Total",Units
0,3.92,2.56,6.48,Preharvest t DM/ha
1,15.60,18.60,16.80,Prehavest Crude Protein
2,44.80,42.80,44.10,Preharvest NDF
3,3.69,2.46,6.15,Postharvest t DM/ha
4,16.00,18.80,17.40,Posthavest Crude Protein
5,47.70,44.20,46.00,Postharvest NDF

In [229]:
# Step 2: Perform some computation, in this case it is over 85 ha so get in terms of mass...
# Only considering ha_total....
# Pre harvest would be an input into the pasture for what initial forage would be
# Post Harvest would likely be considered a parameter
## ## Crude Protein as defined by IFSM -> An estimate of protein content of forage or feed materisal as determined as total nitrogen content multiplied by 6.25 becuase proteins average about 16% nitrogen...
df_1['Amounts']=df_1['GRASS, 85 ha_Total']
df_1 = df_1[['Amounts','Units']]
df_1 = df_1.assign(Product_Flows= ['Crop/Nutrient Yields '+ val.split(" ")[0] for val in df_1['Units']])

df_crop_nutrients = df_1[['Product_Flows','Units','Amounts']]

df_crop_nutrients['Units'] = [''.join(val.split(" ")[1:]) for val in df_crop_nutrients['Units']]
df_crop_nutrients

                      Product_Flows         Units  Amounts
0   Crop/Nutrient Yields Preharvest        tDM/ha     6.48
1    Crop/Nutrient Yields Prehavest  CrudeProtein    16.80
2   Crop/Nutrient Yields Preharvest           NDF    44.10
3  Crop/Nutrient Yields Postharvest        tDM/ha     6.15
4   Crop/Nutrient Yields Posthavest  CrudeProtein    17.40
5  Crop/Nutrient Yields Postharvest           NDF    46.00

It looks like we have a solid table that can be saved until we reach a later point!

### Table 2

- First we will execute a transpose to get it ninto the format we desire
- In this case of this table index 0 corresponds to the units. Row 2 can be discarded as we do not need Standard Deviation

- In addition to this will again create the three columns of Product_Flows, Units and Amounts

In [230]:
# Step 1: as before create a pandas dataframe to see what it will look like
df_2 = pd.DataFrame(table2)
display(df_2)
print('\n')
# Step 2: execute a transpose to get in correct format
## made sure to not include the third row with the standard deviation
df_feed_prod = df_2.iloc[:2].T
## visualize
display(df_feed_prod)
print('\n')

# Step 3: Then reset the index and added in the column names
## rest index
df_feed_prod.reset_index(inplace=True)
## set the column names
df_feed_prod.columns = ['Product_Flows', 'Units','Amounts']
print(df_feed_prod.columns)

# Checked final output
df_feed_prod

,High-quality silage production,Grazed forage consumed,Forage purchased,Grain purchased,"Soybean meal, 44% purchased",User defined feed purchased,Mineral and vitamin mix purchased,Milk production,Fat and protein corrected milk production
0,t DM,t DM,t DM,t DM,t DM,t DM,t DM,L/cow,kg/cow
1,150.0,320.0,641.0,554.0,6.0,28.0,10.0,8419.0,9890.0
2,19.0,42.0,53.0,6.0,4.0,3.0,0.0,15.0,17.0

                                                0       1
High-quality silage production               t DM   150.0
Grazed forage consumed                       t DM   320.0
Forage purchased                             t DM   641.0
Grain purchased                              t DM   554.0
Soybean meal, 44% purchased                  t DM     6.0
User defined feed purchased                  t DM    28.0
Mineral and vitamin mix purchased            t DM    10.0
Milk production                             L/cow  8419.0
Fat and protein corrected milk production  kg/cow  9890.0

Index(['Product_Flows', 'Units', 'Amounts'], dtype='object')

                               Product_Flows   Units Amounts
0             High-quality silage production    t DM   150.0
1                     Grazed forage consumed    t DM   320.0
2                           Forage purchased    t DM   641.0
3                            Grain purchased    t DM   554.0
4                Soybean meal, 44% purchased    t DM     6.0
5                User defined feed purchased    t DM    28.0
6          Mineral and vitamin mix purchased    t DM    10.0
7                            Milk production   L/cow  8419.0
8  Fat and protein corrected milk production  kg/cow  9890.0

### Table 3

- First we will execute a transpose to get it ninto the format we desire
- In this case of this table index 0 corresponds to the units. Row 2 can be discarded as we do not need Standard Deviation

- In addition to this will again create the three columns of Product_Flows, Units and Amounts

In [231]:
# Step 1: as before create a pandas dataframe to see what it will look like
df_3 = pd.DataFrame(table3)
display(df_3)
print(df_3.columns)
print('\n')
# Step 2: execute a transpose to get in correct format
## made sure to not include the third row with the standard deviation
df_nutrient_flows = df_3.iloc[:2].T
## visualize
display(df_nutrient_flows)
print('\n')

# Step 3: Then reset the index and added in the column names
## rest index
df_nutrient_flows.reset_index(inplace=True)
## set the column names
df_nutrient_flows.columns = ['Product_Flows', 'Units','Amounts']
print(df_nutrient_flows.columns)

# Checked final output
df_nutrient_flows

,Nitrogen imported to farm,Nitrogen exported from farm,Nitrogen lost by volatilization,Nitrogen lost by leaching,Nitrogen lost by de/nitrification,Nitrogen lost by runoff,Nitrogen concentration in leachate,Whole-farm excess nitrogen,Phosphorous imported to farm,Phosphorous exported from farm,...,Potassium imported to farm,Potassium exported from farm,Potassium available on farm,Potassium loss through runoff,Whole-farm excess potassium,Carbon imported to farm,Carbon exported from farm,Carbon loss as carbon dioxide,Carbon loss as methane,Carbon loss through runoff
0,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha,ppm,kg/ha,kg/ha,kg/ha,...,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha,kg/ha
1,479.2,124.1,128.9,136.8,47.6,0.3,9.3,47.1,50.8,17.5,...,187.4,25.6,314.8,15.7,146.1,15031.7,1441.5,13237.6,351.3,1.3
2,17.5,0.0,8.2,28.4,5.4,0.2,2.3,29.8,1.7,0.0,...,10.1,0.0,27.2,1.4,10.4,934.7,0.0,935.9,4.2,0.8

Index(['Nitrogen imported to farm', 'Nitrogen exported from farm',
       'Nitrogen lost by volatilization', 'Nitrogen lost by leaching',
       'Nitrogen lost by de/nitrification', 'Nitrogen lost by runoff',
       'Nitrogen concentration in leachate', 'Whole-farm excess nitrogen',
       'Phosphorous imported to farm', 'Phosphorous exported from farm',
       'Phosphorous available on farm',
       'Phosphorous loss in runoff and leachate',
       'Whole-farm excess phosphorus', 'Potassium imported to farm',
       'Potassium exported from farm', 'Potassium available on farm',
       'Potassium loss through runoff', 'Whole-farm excess potassium',
       'Carbon imported to farm', 'Carbon exported from farm',
       'Carbon loss as carbon dioxide', 'Carbon loss as methane',
       'Carbon loss through runoff'],
      dtype='object')

                                              0        1
Nitrogen imported to farm                 kg/ha    479.2
Nitrogen exported from farm               kg/ha    124.1
Nitrogen lost by volatilization           kg/ha    128.9
Nitrogen lost by leaching                 kg/ha    136.8
Nitrogen lost by de/nitrification         kg/ha     47.6
Nitrogen lost by runoff                   kg/ha      0.3
Nitrogen concentration in leachate          ppm      9.3
Whole-farm excess nitrogen                kg/ha     47.1
Phosphorous imported to farm              kg/ha     50.8
Phosphorous exported from farm            kg/ha     17.5
Phosphorous available on farm             kg/ha     49.2
Phosphorous loss in runoff and leachate   kg/ha      1.1
Whole-farm excess phosphorus              kg/ha     32.3
Potassium imported to farm                kg/ha    187.4
Potassium exported from farm              kg/ha     25.6
Potassium available on farm               kg/ha    314.8
Potassium loss through runoff             kg/ha     15.7
Whole-farm excess potassium               kg/ha    146.1
Carbon imported to farm                   kg/ha  15031.7
Carbon exported from farm                 kg/ha   1441.5
Carbon loss as carbon dioxide             kg/ha  13237.6
Carbon loss as methane                    kg/ha    351.3
Carbon loss through runoff                kg/ha      1.3

Index(['Product_Flows', 'Units', 'Amounts'], dtype='object')

                              Product_Flows   Units  Amounts
0                 Nitrogen imported to farm   kg/ha    479.2
1               Nitrogen exported from farm   kg/ha    124.1
2           Nitrogen lost by volatilization   kg/ha    128.9
3                 Nitrogen lost by leaching   kg/ha    136.8
4         Nitrogen lost by de/nitrification   kg/ha     47.6
5                   Nitrogen lost by runoff   kg/ha      0.3
6        Nitrogen concentration in leachate     ppm      9.3
7                Whole-farm excess nitrogen   kg/ha     47.1
8              Phosphorous imported to farm   kg/ha     50.8
9            Phosphorous exported from farm   kg/ha     17.5
10            Phosphorous available on farm   kg/ha     49.2
11  Phosphorous loss in runoff and leachate   kg/ha      1.1
12             Whole-farm excess phosphorus   kg/ha     32.3
13               Potassium imported to farm   kg/ha    187.4
14             Potassium exported from farm   kg/ha     25.6
15              Potassium available on farm   kg/ha    314.8
16            Potassium loss through runoff   kg/ha     15.7
17              Whole-farm excess potassium   kg/ha    146.1
18                  Carbon imported to farm   kg/ha  15031.7
19                Carbon exported from farm   kg/ha   1441.5
20            Carbon loss as carbon dioxide   kg/ha  13237.6
21                   Carbon loss as methane   kg/ha    351.3
22               Carbon loss through runoff   kg/ha      1.3

### Table 4

- First we will execute a transpose to get it ninto the format we desire
- In this case of this table index 0 corresponds to the units. Row 2 can be discarded as we do not need Standard Deviation

- In addition to this will again create the three columns of Product_Flows, Units and Amounts

In [232]:
# Step 1: as before create a pandas dataframe to see what it will look like
df_4 = pd.DataFrame(table4)
display(df_4)
print('\n')
# Step 2: execute a transpose to get in correct format
## made sure to not include the third row with the standard deviation
df_economics = df_4.iloc[:2].T
## visualize
display(df_economics)
print('\n')

# Step 3: Then reset the index and added in the column names
## rest index
df_economics.reset_index(inplace=True)
## set the column names
df_economics.columns = ['Product_Flows', 'Units','Amounts']
print(df_economics.columns)

# Checked final output
df_economics

,Equipment cost,Facilities cost,Energy cost,Labor cost,"Seed, fertilizer and chemical cost",Net purchased feed and bedding cost,Animal purchase and livestock expense,Milk hauling and marketing fees,Property tax,Income from milk sales,Income from animal sales,Return to management and unpaid factors
0,$,$,$,$,$,$,$,$,$,$,$,$
1,41976.0,86883.0,20027.0,67797.0,14863.0,279079.0,74625.0,33677.0,5979.0,673539.0,53648.0,102281.0
2,246.0,446.0,122.0,285.0,0.0,9281.0,0.0,59.0,0.0,1173.0,0.0,9381.0

                                          0         1
Equipment cost                            $   41976.0
Facilities cost                           $   86883.0
Energy cost                               $   20027.0
Labor cost                                $   67797.0
Seed, fertilizer and chemical cost        $   14863.0
Net purchased feed and bedding cost       $  279079.0
Animal purchase and livestock expense     $   74625.0
Milk hauling and marketing fees           $   33677.0
Property tax                              $    5979.0
Income from milk sales                    $  673539.0
Income from animal sales                  $   53648.0
Return to management and unpaid factors   $  102281.0

Index(['Product_Flows', 'Units', 'Amounts'], dtype='object')

                              Product_Flows Units   Amounts
0                            Equipment cost     $   41976.0
1                           Facilities cost     $   86883.0
2                               Energy cost     $   20027.0
3                                Labor cost     $   67797.0
4        Seed, fertilizer and chemical cost     $   14863.0
5       Net purchased feed and bedding cost     $  279079.0
6     Animal purchase and livestock expense     $   74625.0
7           Milk hauling and marketing fees     $   33677.0
8                              Property tax     $    5979.0
9                    Income from milk sales     $  673539.0
10                 Income from animal sales     $   53648.0
11  Return to management and unpaid factors     $  102281.0

### Table 5 - DOUBLE CHECK!

- First we will execute a transpose to get it ninto the format we desire
- In this case of this table index 0 corresponds to the units. Row 2 can be discarded as we do not need Standard Deviation

- In addition to this will again create the three columns of Product_Flows, Units and Amounts

In [235]:
# Step 1: as before create a pandas dataframe to see what it will look like
df_5 = pd.DataFrame(table5)
display(df_5)
print('\n')
# Step 2: execute a transpose to get in correct format
## made sure to not include the third row with the standard deviation
df_emissions = df_5.iloc[:2].T
## visualize
display(df_emissions)
print('\n')

# Step 3: Then reset the index and added in the column names
## rest index
df_emissions.reset_index(inplace=True)
## set the column names
df_emissions.columns = ['Product_Flows', 'Units','Amounts']
print(df_emissions.columns)

# Checked final output
df_emissions

,Ammonia_ Housing facility,Ammonia_ Manure storage,Ammonia_ Field application,Ammonia_ Grazing,Ammonia_Total farm,Ozone Forming VOC_ Silo face,Ozone Forming VOC_ Silage feeding,Ozone Forming VOC_ Housing manure,Ozone Forming VOC_ Field / grazing,Methane_ Animal,Nitrous Oxide_ Farmland,Nitrous Oxide_ Indirect sources,Biogenic Carbon Dioxide_ Net land and feed,Biogenic Carbon Dioxide_Anthropogenic Carbon Dioxide
0,15.766,1.453,0.017,11.593,---,0.0,0.004,0.007,0.056,0.001,0.021,0.004,---,---
1,3153.000,291.000,3.000,2319.000,---,0.0,1.000,1.000,11.000,0.000,4.000,1.000,---,---
2,7.435,0.440,0.004,6.615,-6.154,0.0,0.002,0.002,0.004,0.000,0.004,0.004,-20.644,1.496
3,1487.000,88.000,1.000,1323.000,-1231.0,0.0,0.000,0.000,1.000,0.000,1.000,1.000,-4129.0,299.0
4,2713.800,160.400,1.600,2414.400,-2246.3,0.0,0.600,0.600,1.600,0.200,1.400,1.500,-7534.9,546.1
5,542758.000,32086.000,311.000,482885.000,-449254.0,7.0,129.000,119.000,328.000,36.000,288.000,302.000,-1506981.0,109229.0

                                                         0       1
Ammonia_ Housing facility                           15.766  3153.0
Ammonia_ Manure storage                              1.453   291.0
Ammonia_ Field application                           0.017     3.0
Ammonia_ Grazing                                    11.593  2319.0
Ammonia_Total farm                                     ---     ---
Ozone Forming VOC_ Silo face                           0.0     0.0
Ozone Forming VOC_ Silage feeding                    0.004     1.0
Ozone Forming VOC_ Housing manure                    0.007     1.0
Ozone Forming VOC_ Field / grazing                   0.056    11.0
Methane_ Animal                                      0.001     0.0
Nitrous Oxide_ Farmland                              0.021     4.0
Nitrous Oxide_ Indirect sources                      0.004     1.0
Biogenic Carbon Dioxide_ Net land and feed             ---     ---
Biogenic Carbon Dioxide_Anthropogenic Carbon Di...     ---     ---

Index(['Product_Flows', 'Units', 'Amounts'], dtype='object')

                                        Product_Flows   Units Amounts
0                           Ammonia_ Housing facility  15.766  3153.0
1                             Ammonia_ Manure storage   1.453   291.0
2                          Ammonia_ Field application   0.017     3.0
3                                    Ammonia_ Grazing  11.593  2319.0
4                                  Ammonia_Total farm     ---     ---
5                        Ozone Forming VOC_ Silo face     0.0     0.0
6                   Ozone Forming VOC_ Silage feeding   0.004     1.0
7                   Ozone Forming VOC_ Housing manure   0.007     1.0
8                  Ozone Forming VOC_ Field / grazing   0.056    11.0
9                                     Methane_ Animal   0.001     0.0
10                            Nitrous Oxide_ Farmland   0.021     4.0
11                    Nitrous Oxide_ Indirect sources   0.004     1.0
12         Biogenic Carbon Dioxide_ Net land and feed     ---     ---
13  Biogenic Carbon Dioxide_Anthropogenic Carbon D...     ---     ---

### Table 6 -

DOUBLE CHECK BUT LOOKS GOOD!

In [145]:
print(table6)
for count, k in enumerate(table6):
    if len(table6[k]) != 3:
        print(k)
        print(len(table6[k]))

{'Water Use_ Feed production, rainfall': ['Mg', 596423.0, 37417.0], 'Water Use_ Evapotranspiration': [' Mg', 564142.0, 33732.0], 'Water Use_ Drinking': [' Mg', 6033.0, 34.0], 'Water Use_ Animal cooling and dust control': ['Mg', 52.0, 34.0], 'Water Use_ Parlor and equipment cleaning': ['Mg', 1825.0, 0.0], 'Water Use_ Production of purchased feed and inputs': ['Mg', 478540.0, 36824.0], 'Water Use_ Not allocated to milk production': [' kg', -186851.0, 2605.0], 'Water Use_Green water footprint': [' kg/kg FPCM', 639.0, 11.0], 'Water Use_Blue water footprint': ['kg/kg FPCM', 223.5, 17.0], 'Water Use_Reactive Nitrogen Loss': [], 'Water Use_ Ammonia emission': [' kg', 10953.0, 695.0], 'Water Use_ Nitrate leaching and runoff': ['kg', 11649.0, 2415.0], 'Water Use_ De/nitrification emissions': [' kg', 4001.0, 462.0], 'Water Use_ Fuel combustion emissions': ['kg', 82.0, 1.0], 'Water Use_ Production of resource inputs': ['kg', 466848.0, 8311.0], 'Water Use_Reactive nitrogen footprint': ['g/kg FPCM', 13.56, 1.21], 'Water Use_Energy Use': [], 'Water Use_ Feed production': ['MJ', 117592.0, 2857.0], 'Water Use_ Animal feeding': [' MJ', 104097.0, 3164.0], 'Water Use_ Manure handling': ['MJ', 48747.0, 520.0], 'Water Use_ Milking and milk cooling': [' MJ', 389252.0, 678.0], 'Water Use_ Animal housing ventilation and lighting': ['MJ', 70927.0, 0.0], 'Water Use_Energy footprint': [' MJ/kg FPCM', 2.2, 0.04], 'Water Use_Greenhouse Gas Emissions (CO2e)': [], 'Water Use_ Animal emissions': [' kg', 934537.0, 3234.0], 'Water Use_ Manure emissions': [' kg', 221202.0, 16093.0], 'Water Use_ Direct and indirect land emissions': [' kg', 156165.0, 14333.0], 'Water Use_ Net biogenic carbon dioxide emissions': ['kg', -449254.0, 0.0], 'Water Use_ Anthropogenic carbon dioxide emissions': [' kg', 109229.0, 374.0], 'Water Use_Carbon footprint without biogenic CO2': ['kg/kg FPCM', 0.86, 0.01], 'Water Use_Carbon footprint with biogenic CO2': [' kg/kg FPCM', 0.654, 0.01]}
Water Use_Reactive Nitrogen Loss
0
Water Use_Energy Use
0
Water Use_Greenhouse Gas Emissions (CO2e)
0

In [236]:
# Step 1: as before create a pandas dataframe to see what it will look like
df_6 = pd.DataFrame(table6)
display(df_6)
print('\n')
# Step 2: execute a transpose to get in correct format
## made sure to not include the third row with the standard deviation
df_enve_footprint = df_6.iloc[:2].T
## visualize
display(df_enve_footprint)
print('\n')

# Step 3: Then reset the index and added in the column names
## rest index
df_enve_footprint.reset_index(inplace=True)
## set the column names
df_enve_footprint.columns = ['Product_Flows', 'Units','Amounts']
print(df_enve_footprint.columns)

# Checked final output
df_enve_footprint

,"Water Use_ Feed production, rainfall",Water Use_ Evapotranspiration,Water Use_ Drinking,Water Use_ Animal cooling and dust control,Water Use_ Parlor and equipment cleaning,Water Use_ Production of purchased feed and inputs,Water Use_ Not allocated to milk production,Water Use_Green water footprint,Water Use_Blue water footprint,Reactive Nitrogen Loss_ Ammonia emission,...,Energy Use_ Milking and milk cooling,Energy Use_ Animal housing ventilation and lighting,Energy Use_Energy footprint,Greenhouse Gas Emissions (CO2e)_ Animal emissions,Greenhouse Gas Emissions (CO2e)_ Manure emissions,Greenhouse Gas Emissions (CO2e)_ Direct and indirect land emissions,Greenhouse Gas Emissions (CO2e)_ Net biogenic carbon dioxide emissions,Greenhouse Gas Emissions (CO2e)_ Anthropogenic carbon dioxide emissions,Greenhouse Gas Emissions (CO2e)_Carbon footprint without biogenic CO2,Greenhouse Gas Emissions (CO2e)_Carbon footprint with biogenic CO2
0,Mg,Mg,Mg,Mg,Mg,Mg,kg,kg/kg FPCM,kg/kg FPCM,kg,...,MJ,MJ,MJ/kg FPCM,kg,kg,kg,kg,kg,kg/kg FPCM,kg/kg FPCM
1,596423.0,564142.0,6033.0,52.0,1825.0,478540.0,-186851.0,639.0,223.5,10953.0,...,389252.0,70927.0,2.2,934537.0,221202.0,156165.0,-449254.0,109229.0,0.86,0.654
2,37417.0,33732.0,34.0,34.0,0.0,36824.0,2605.0,11.0,17.0,695.0,...,678.0,0.0,0.04,3234.0,16093.0,14333.0,0.0,374.0,0.01,0.01

                                                              0         1
Water Use_ Feed production, rainfall                         Mg  596423.0
Water Use_ Evapotranspiration                                Mg  564142.0
Water Use_ Drinking                                          Mg    6033.0
Water Use_ Animal cooling and dust control                   Mg      52.0
Water Use_ Parlor and equipment cleaning                     Mg    1825.0
Water Use_ Production of purchased feed and inputs           Mg  478540.0
Water Use_ Not allocated to milk production                  kg -186851.0
Water Use_Green water footprint                      kg/kg FPCM     639.0
Water Use_Blue water footprint                       kg/kg FPCM     223.5
Reactive Nitrogen Loss_ Ammonia emission                     kg   10953.0
Reactive Nitrogen Loss_ Nitrate leaching and ru...           kg   11649.0
Reactive Nitrogen Loss_ De/nitrification emissions           kg    4001.0
Reactive Nitrogen Loss_ Fuel combustion emissions            kg      82.0
Reactive Nitrogen Loss_ Production of resource ...           kg  466848.0
Reactive Nitrogen Loss_Reactive nitrogen footprint    g/kg FPCM     13.56
Energy Use_ Feed production                                  MJ  117592.0
Energy Use_ Animal feeding                                   MJ  104097.0
Energy Use_ Manure handling                                  MJ   48747.0
Energy Use_ Milking and milk cooling                         MJ  389252.0
Energy Use_ Animal housing ventilation and ligh...           MJ   70927.0
Energy Use_Energy footprint                          MJ/kg FPCM       2.2
Greenhouse Gas Emissions (CO2e)_ Animal emissions            kg  934537.0
Greenhouse Gas Emissions (CO2e)_ Manure emissions            kg  221202.0
Greenhouse Gas Emissions (CO2e)_ Direct and ind...           kg  156165.0
Greenhouse Gas Emissions (CO2e)_ Net biogenic c...           kg -449254.0
Greenhouse Gas Emissions (CO2e)_ Anthropogenic ...           kg  109229.0
Greenhouse Gas Emissions (CO2e)_Carbon footprin...   kg/kg FPCM      0.86
Greenhouse Gas Emissions (CO2e)_Carbon footprin...   kg/kg FPCM     0.654

Index(['Product_Flows', 'Units', 'Amounts'], dtype='object')

                                        Product_Flows        Units   Amounts
0                Water Use_ Feed production, rainfall           Mg  596423.0
1                       Water Use_ Evapotranspiration           Mg  564142.0
2                                 Water Use_ Drinking           Mg    6033.0
3          Water Use_ Animal cooling and dust control           Mg      52.0
4            Water Use_ Parlor and equipment cleaning           Mg    1825.0
5   Water Use_ Production of purchased feed and in...           Mg  478540.0
6         Water Use_ Not allocated to milk production           kg -186851.0
7                     Water Use_Green water footprint   kg/kg FPCM     639.0
8                      Water Use_Blue water footprint   kg/kg FPCM     223.5
9            Reactive Nitrogen Loss_ Ammonia emission           kg   10953.0
10  Reactive Nitrogen Loss_ Nitrate leaching and r...           kg   11649.0
11  Reactive Nitrogen Loss_ De/nitrification emiss...           kg    4001.0
12  Reactive Nitrogen Loss_ Fuel combustion emissions           kg      82.0
13  Reactive Nitrogen Loss_ Production of resource...           kg  466848.0
14  Reactive Nitrogen Loss_Reactive nitrogen footp...    g/kg FPCM     13.56
15                        Energy Use_ Feed production           MJ  117592.0
16                         Energy Use_ Animal feeding           MJ  104097.0
17                        Energy Use_ Manure handling           MJ   48747.0
18               Energy Use_ Milking and milk cooling           MJ  389252.0
19  Energy Use_ Animal housing ventilation and lig...           MJ   70927.0
20                        Energy Use_Energy footprint   MJ/kg FPCM       2.2
21  Greenhouse Gas Emissions (CO2e)_ Animal emissions           kg  934537.0
22  Greenhouse Gas Emissions (CO2e)_ Manure emissions           kg  221202.0
23  Greenhouse Gas Emissions (CO2e)_ Direct and in...           kg  156165.0
24  Greenhouse Gas Emissions (CO2e)_ Net biogenic ...           kg -449254.0
25  Greenhouse Gas Emissions (CO2e)_ Anthropogenic...           kg  109229.0
26  Greenhouse Gas Emissions (CO2e)_Carbon footpri...   kg/kg FPCM      0.86
27  Greenhouse Gas Emissions (CO2e)_Carbon footpri...   kg/kg FPCM     0.654

# We have developed 6 different dataframes for our data
we will display them below

We still need to verify some of the values

In [ ]:
print("Table 1: Average crop yields and nutritive contents over a 25 year analysis of a 85 ha dairy farm.\n")
display()

# Markdown Shocasing the Output Textfile for a Particular Portion of the Summary File

Ammonia
	   Housing facility          0.077      15     0.023       5       8.2      1647
	   Manure storage            0.316      63     0.056      11      20.3      4064
	   Field application         1.326     265     0.069      14      25.3      5055
	   Grazing                   0.142      28     0.035       7      12.8      2553
	      Total farm             1.552     310     0.182      36      66.6     13319

	Hydrogen Sulfide
	   Housing facility          0.000       0     0.000       0       0.1        11
	   Manure storage            0.007       1     0.002       0       0.6       111
	   Field application         0.038       8     0.002       0       0.7       141
	   Grazing                   0.000       0     0.000       0       0.0         1
	      Total farm             0.041       8     0.004       1       1.3       263

	Ozone Forming VOC
	   Silo face                 0.000       0     0.000       0       0.0         7
	   Silage feeding            0.004       1     0.002       0       0.6       129
	   Housing manure            0.001       0     0.000       0       0.2        32
	   Manure storage            0.019       4     0.003       1       1.2       238
	   Field / grazing           0.056      11     0.004       1       1.6       328
	      Total farm             0.065      13     0.010       2       3.7       734

	Methane
	   Animal                    0.525     105     0.453      91     165.2     33035
	   Housing manure            0.100      20     0.028       6      10.1      2027
	   Manure storage            0.198      40     0.061      12      22.2      4440
	   Field application         0.017       3     0.004       1       1.6       311
	      Total farm             0.683     137     0.545     109     199.1     39813

	Nitrous Oxide
	   Animal                    0.001       0     0.000       0       0.2        36
	   Housing manure            0.007       1     0.002       0       0.6       119
	   Farmland                  0.021       4     0.004       1       1.4       288
	   Indirect sources          0.004       1     0.004       1       1.5       302
	      Total farm             0.027       5     0.010       2       3.7       744

	Biogenic Carbon Dioxide
	   Housing facility         15.766    3153     7.435    1487    2713.8    542758
	   Manure storage            1.453     291     0.440      88     160.4     32086
	   Grazing                  11.593    2319     6.615    1323    2414.4    482885
	   Net land and feed           ---     ---   -20.644   -4129   -7534.9  -1506981
	      Total farm               ---     ---    -6.154   -1231   -2246.3   -449254

	Anthropogenic Carbon Dioxide   ---     ---     1.496     299     546.1    109229

# Testing Making Unique Keys For Each Row...
    - This way we have all the strings that are keys dealing with the rows are all unique so then we can take care of this issue...

    - Essentially now what is needed is to make a unique dictionary for each table...

    - Then after we do this we will go back through and get each dictionary and then make a CSV or Exccel or JSON for that...

    - Will need to also add the columns somehow maybe??? IDK how one would do that tbh

In [11]:
f = open("IFSM_srm1.txt", 'r')
# get all lines
lines = f.readlines()

# function to detemrine if string is actually a float...
def isfloat(num):
    try:
        float(num)
        return True
    except ValueError:
        return False

# okay here is example what I am trying to get..
## we set a dictionary to save the data to...
### first element of each list will be the key and rest of the elements will be the elements of a new list set as the value to that key
data_save = {}

## So we will be going through all of the table indexes..
print(table_idxs)
for idx_trio in table_idxs:
    str_test = lines[idx_trio[1]+2:idx_trio[2]]
    #print(idx_trio)
    #print(str_test)
    for lne in str_test:
        
        # first we do a replacement of the tab and newline characters
        a = lne.replace('\t',"").replace('\n',"")
        # after this point we need to split by two spaces so that we still have any row headers by can also split up everything 
        b = a.split('  ') 

        # using list comprehension we get rid of all empty strings
        c =[x for x in b if len(x)>0 ]

        #print("list of data", c)
        # ADDED CONDITION: IF THERE IS JUST A A BLANK LINE WHICH AT THIS POINT WOULD BE [''] then dont add it to the dictionary....
        if len(c) > 0:
            # Then we make sure that the first element is a string and all other values are converted to be floats
            # d = [c[val] if val == 0 else float(c[val]) if isfloat(c[val])==False else c[val] for val in range(len(c))]

            ## if it is index 0 then keep it as is... 
            ## then after index 0 we will then check to see if value is a float or not...
            d = []
            for val in range(len(c)):
                if val == 0:
                    d.append(c[val])
                elif isfloat(c[val]):
                    d.append(float(c[val]))

                else:
                    d.append(c[val])




            # now in this last part we have a list with numerical data and a row header... this row header will be set as a key in the dictionary
            ## then the rest of the list will be set as the value to that key
            data_save[d[0]]=d[1:]

data_save

[[4, 9, 15], [21, 24, 35], [41, 44, 72], [78, 81, 97], [103, 107, 153], [159, 162, 204]]

{'GRASS, 85 ha': [],
 'Cutting 1': [3.92, 15.6, 44.8, 3.69, 16.0, 47.7],
 'Cutting 2': [2.56, 18.6, 42.8, 2.46, 18.8, 44.2],
 'Total': [6.48, 16.8, 44.1, 6.15, 17.4, 46.0],
 'High-quality silage production': [' t DM', 150.0, 19.0],
 'Grazed forage consumed': [' t DM', 320.0, 42.0],
 'Forage purchased': [' t DM', 641.0, 53.0],
 'Grain purchased': ['t DM', 554.0, 6.0],
 'Soybean meal, 44% purchased': ['t DM', 6.0, 4.0],
 'User defined feed purchased': ['t DM', 28.0, 3.0],
 'Mineral and vitamin mix purchased': ['t DM', 10.0, 0.0],
 'Milk production': [' L/cow', 8419.0, 15.0],
 'Fat and protein corrected milk production': ['kg/cow', 9890.0, 17.0],
 'Nitrogen imported to farm': [' kg/ha', 479.2, 17.5],
 'Nitrogen exported from farm': [' kg/ha', 124.1, 0.0],
 'Nitrogen lost by volatilization': [' kg/ha', 128.9, 8.2],
 'Nitrogen lost by leaching': [' kg/ha', 136.8, 28.4],
 'Nitrogen lost by de/nitrification': [' kg/ha', 47.6, 5.4],
 'Nitrogen lost by runoff': [' kg/ha', 0.3, 0.2],
 'Nitrogen concentration in leachate': [' ppm', 9.3, 2.3],
 'Whole-farm excess nitrogen': ['kg/ha', 47.1, 29.8],
 'Phosphorous imported to farm': ['kg/ha', 50.8, 1.7],
 'Phosphorous exported from farm': ['kg/ha', 17.5, 0.0],
 'Phosphorous available on farm': [' kg/ha', 49.2, 4.2],
 'Phosphorous loss in runoff and leachate': [' kg/ha', 1.1, 0.7],
 'Whole-farm excess phosphorus': ['kg/ha', 32.3, 1.7],
 'Potassium imported to farm': ['kg/ha', 187.4, 10.1],
 'Potassium exported from farm': ['kg/ha', 25.6, 0.0],
 'Potassium available on farm': [' kg/ha', 314.8, 27.2],
 'Potassium loss through runoff': [' kg/ha', 15.7, 1.4],
 'Whole-farm excess potassium': [' kg/ha', 146.1, 10.4],
 'Carbon imported to farm': [' kg/ha', 15031.7, 934.7],
 'Carbon exported from farm': [' kg/ha', 1441.5, 0.0],
 'Carbon loss as carbon dioxide': [' kg/ha', 13237.6, 935.9],
 'Carbon loss as methane': ['kg/ha', 351.3, 4.2],
 'Carbon loss through runoff': ['kg/ha', 1.3, 0.8],
 'Equipment cost': [' $', 41976.0, 246.0],
 'Facilities cost': ['$', 86883.0, 446.0],
 'Energy cost': ['$', 20027.0, 122.0],
 'Labor cost': [' $', 67797.0, 285.0],
 'Seed, fertilizer and chemical cost': [' $', 14863.0, 0.0],
 'Net purchased feed and bedding cost': ['$', 279079.0, 9281.0],
 'Animal purchase and livestock expense': ['$', 74625.0, 0.0],
 'Milk hauling and marketing fees': ['$', 33677.0, 59.0],
 'Property tax': [' $', 5979.0, 0.0],
 'Income from milk sales': [' $', 673539.0, 1173.0],
 'Income from animal sales': [' $', 53648.0, 0.0],
 'Return to management and unpaid factors': ['$', 102281.0, 9381.0],
 'Ammonia': [],
 ' Housing facility': [15.766, 3153.0, 7.435, 1487.0, 2713.8, 542758.0],
 ' Manure storage': [1.453, 291.0, 0.44, 88.0, 160.4, 32086.0],
 ' Field application': [0.017, 3.0, 0.004, 1.0, 1.6, 311.0],
 ' Grazing': [11.593, 2319.0, 6.615, 1323.0, 2414.4, 482885.0],
 'Total farm': [' ---', ' ---', -6.154, -1231.0, -2246.3, -449254.0],
 'Hydrogen Sulfide': [],
 'Ozone Forming VOC': [],
 ' Silo face': [0.0, 0.0, 0.0, 0.0, 0.0, 7.0],
 ' Silage feeding': [0.004, 1.0, 0.002, 0.0, 0.6, 129.0],
 ' Housing manure': [0.007, 1.0, 0.002, 0.0, 0.6, 119.0],
 ' Field / grazing': [0.056, 11.0, 0.004, 1.0, 1.6, 328.0],
 'Methane': [],
 ' Animal': [0.001, 0.0, 0.0, 0.0, 0.2, 36.0],
 'Nitrous Oxide': [],
 ' Farmland': [0.021, 4.0, 0.004, 1.0, 1.4, 288.0],
 ' Indirect sources': [0.004, 1.0, 0.004, 1.0, 1.5, 302.0],
 'Biogenic Carbon Dioxide': [],
 ' Net land and feed': [' ---', ' ---', -20.644, -4129.0, -7534.9, -1506981.0],
 'Anthropogenic Carbon Dioxide': [' ---',
  ' ---',
  1.496,
  299.0,
  546.1,
  109229.0],
 'Water Use': [],
 ' Feed production, rainfall': ['Mg', 596423.0, 37417.0],
 ' Evapotranspiration': [' Mg', 564142.0, 33732.0],
 ' Drinking': [' Mg', 6033.0, 34.0],
 ' Animal cooling and dust control': ['Mg', 52.0, 34.0],
 ' Parlor and equipment cleaning': ['Mg', 1825.0, 0.0],
 ' Production of purchased feed and inputs': ['Mg', 478540.0, 36824.0],
 ' Not allocated to milk production': [' kg', -186851.0, 2605.0],
 'Green water footprint': [' kg/kg FPCM', 639.0, 11.0],
 'Blue water footprint': ['kg/kg FPCM', 223.5, 17.0],
 'Reactive Nitrogen Loss': [],
 ' Ammonia emission': [' kg', 10953.0, 695.0],
 ' Nitrate leaching and runoff': ['kg', 11649.0, 2415.0],
 ' De/nitrification emissions': [' kg', 4001.0, 462.0],
 ' Fuel combustion emissions': ['kg', 82.0, 1.0],
 ' Production of resource inputs': ['kg', 466848.0, 8311.0],
 'Reactive nitrogen footprint': ['g/kg FPCM', 13.56, 1.21],
 'Energy Use': [],
 ' Feed production': ['MJ', 117592.0, 2857.0],
 ' Animal feeding': [' MJ', 104097.0, 3164.0],
 ' Manure handling': ['MJ', 48747.0, 520.0],
 ' Milking and milk cooling': [' MJ', 389252.0, 678.0],
 ' Animal housing ventilation and lighting': ['MJ', 70927.0, 0.0],
 'Energy footprint': [' MJ/kg FPCM', 2.2, 0.04],
 'Greenhouse Gas Emissions (CO2e)': [],
 ' Animal emissions': [' kg', 934537.0, 3234.0],
 ' Manure emissions': [' kg', 221202.0, 16093.0],
 ' Direct and indirect land emissions': [' kg', 156165.0, 14333.0],
 ' Net biogenic carbon dioxide emissions': ['kg', -449254.0, 0.0],
 ' Anthropogenic carbon dioxide emissions': [' kg', 109229.0, 374.0],
 'Carbon footprint without biogenic CO2': ['kg/kg FPCM', 0.86, 0.01],
 'Carbon footprint with biogenic CO2': [' kg/kg FPCM', 0.654, 0.01]}

# Okaay so basically need to do this such that i maintain the header columns, and also the row names as well...

so the dictionary should ahve rows, columns keys and then the other keys correspond to the data for each row...

# for formatting...

### TRY USING THIS METHOD FOR DIRECT FORMATTTING .... AND CONVERSION AFTER GETTING RID OF THE NONSESNSE>>.

In [283]:
## Need to determine at what indexes the table breaks... then we can fully split everything up
# # for this we will be looking specifically for the -----------------------

# LOGICAL NOT WORKS FOR GETTING RID OF STUFF....
import csv
with open("IFSM_srm1.txt", 'r') as f:
    lines = f.readlines()

# Convert the list to a NumPy array
test_array = np.array(lines)

# Define the conditions for the truth series
ts1 = test_array == '\t__________________________________________________________________________________\n' 
ts2 = test_array == '\t_________________________________________________________________________________\n'
# Combine conditions using logical OR
combined_condition = np.logical_or(ts1, ts2)

# Use the bitwise NOT operator (~) to exclude lines matching the conditions
filtered_lines = test_array[~combined_condition]

# Print the filtered lines
print(filtered_lines)

# print(res_array[0])
# print(test_array[res_array[0]])

csv_filename = "output_data.csv"

with open(csv_filename, mode='w', newline='') as csv_file:
    writer = csv.writer(csv_file, delimiter=',')
    
    for row in filtered_lines:
        writer.writerow(row)

['\n' '\n'
 '\tAverage crop yields and nutritive contents over a 25 year analysis of a 85 ha\n'
 '\tdairy farm.\n' '\n'
 '\t               --------- Preharvest --------     ----------- Postharvest -------\n'
 '\t                 Yield       Crude                   Yield       Crude\n'
 '\t               (t DM/ha)    Protein      NDF       (t DM/ha)    Protein      NDF\n'
 '\n' '\tGRASS, 85 ha\n'
 '\t  Cutting 1       3.92       15.6       44.8          3.69       16.0       47.7\n'
 '\t  Cutting 2       2.56       18.6       42.8          2.46       18.8       44.2\n'
 '\t    Total         6.48       16.8       44.1          6.15       17.4       46.0\n'
 '\n' '\n' '\n'
 '\tAnnual feed production and use for a 25 year analysis of a dairy farm with 200\n'
 '\tcows and 129 other stock on 85 hectares of land.\n' '\n'
 '\t                                                 Unit        Mean          SD\n'
 '\n'
 '\t  High-quality silage production                 t DM         150          19\n'
 '\t  Grazed forage consumed                         t DM         320          42\n'
 '\t  Forage purchased                               t DM         641          53\n'
 '\t  Grain purchased                                t DM         554           6\n'
 '\t  Soybean meal, 44% purchased                    t DM           6           4\n'
 '\t  User defined feed purchased                    t DM          28           3\n'
 '\t  Mineral and vitamin mix purchased              t DM          10           0\n'
 '\t  Milk production                               L/cow        8419          15\n'
 '\t  Fat and protein corrected milk production    kg/cow        9890          17\n'
 '\n' '\n' '\n'
 '\tNutrients available, used, and lost to the environment for a 25 year analysis of\n'
 '\ta farm with 200 cows and 129 other stock on 85 hectares of land.\n'
 '\n'
 '\t                                                 Unit        Mean          SD\n'
 '\n'
 '\t  Nitrogen imported to farm                     kg/ha       479.2        17.5\n'
 '\t  Nitrogen exported from farm                   kg/ha       124.1         0.0\n'
 '\t  Nitrogen lost by volatilization               kg/ha       128.9         8.2\n'
 '\t  Nitrogen lost by leaching                     kg/ha       136.8        28.4\n'
 '\t  Nitrogen lost by de/nitrification             kg/ha        47.6         5.4\n'
 '\t  Nitrogen lost by runoff                       kg/ha         0.3         0.2\n'
 '\t  Nitrogen concentration in leachate             ppm          9.3         2.3\n'
 '\t  Whole-farm excess nitrogen                    kg/ha        47.1        29.8\n'
 '\n'
 '\t  Phosphorous imported to farm                  kg/ha        50.8         1.7\n'
 '\t  Phosphorous exported from farm                kg/ha        17.5         0.0\n'
 '\t  Phosphorous available on farm                 kg/ha        49.2         4.2\n'
 '\t  Phosphorous loss in runoff and leachate       kg/ha         1.1         0.7\n'
 '\t  Whole-farm excess phosphorus                  kg/ha        32.3         1.7\n'
 '\n'
 '\t  Potassium imported to farm                    kg/ha       187.4        10.1\n'
 '\t  Potassium exported from farm                  kg/ha        25.6         0.0\n'
 '\t  Potassium available on farm                   kg/ha       314.8        27.2\n'
 '\t  Potassium loss through runoff                 kg/ha        15.7         1.4\n'
 '\t  Whole-farm excess potassium                   kg/ha       146.1        10.4\n'
 '\n'
 '\t  Carbon imported to farm                       kg/ha     15031.7       934.7\n'
 '\t  Carbon exported from farm                     kg/ha      1441.5         0.0\n'
 '\t  Carbon loss as carbon dioxide                 kg/ha     13237.6       935.9\n'
 '\t  Carbon loss as methane                        kg/ha       351.3         4.2\n'
 '\t  Carbon loss through runoff                    kg/ha         1.3         0.8\n'
 '\n' '\n' '\n'
 '\tAnnual production costs and return to management for a 25 year analysis of a \n'
 '\tfarm with 200 cows and 129 other stock on 85 hectares of land.\n' '\n'
 '\t                                                 Unit        Mean          SD\n'
 '\n'
 '\t  Equipment cost                                   $        41976         246\n'
 '\t  Facilities cost                                  $        86883         446\n'
 '\t  Energy cost                                      $        20027         122\n'
 '\t  Labor cost                                       $        67797         285\n'
 '\t  Seed, fertilizer and chemical cost               $        14863           0\n'
 '\t  Net purchased feed and bedding cost              $       279079        9281\n'
 '\t  Animal purchase and livestock expense            $        74625           0\n'
 '\t  Milk hauling and marketing fees                  $        33677          59\n'
 '\t  Property tax                                     $         5979           0\n'
 '\n'
 '\t  Income from milk sales                           $       673539        1173\n'
 '\t  Income from animal sales                         $        53648           0\n'
 '\n'
 '\t  Return to management and unpaid factors          $       102281        9381\n'
 '\n' '\n' '\n'
 '\tDaily and annual emissions of important gaseous compounds for a dairy farm with\n'
 '\t200 cows and 129 other stock on 85 hectares of land.\n' '\n'
 '\t                             Maximum daily     Average daily      Total annual\n'
 '\t                             kg/cow     kg     kg/cow     kg     kg/cow      kg\n'
 '\n' '\tAmmonia\n'
 '\t   Housing facility          0.077      15     0.023       5       8.2      1647\n'
 '\t   Manure storage            0.316      63     0.056      11      20.3      4064\n'
 '\t   Field application         1.326     265     0.069      14      25.3      5055\n'
 '\t   Grazing                   0.142      28     0.035       7      12.8      2553\n'
 '\t      Total farm             1.552     310     0.182      36      66.6     13319\n'
 '\n' '\tHydrogen Sulfide\n'
 '\t   Housing facility          0.000       0     0.000       0       0.1        11\n'
 '\t   Manure storage            0.007       1     0.002       0       0.6       111\n'
 '\t   Field application         0.038       8     0.002       0       0.7       141\n'
 '\t   Grazing                   0.000       0     0.000       0       0.0         1\n'
 '\t      Total farm             0.041       8     0.004       1       1.3       263\n'
 '\n' '\tOzone Forming VOC\n'
 '\t   Silo face                 0.000       0     0.000       0       0.0         7\n'
 '\t   Silage feeding            0.004       1     0.002       0       0.6       129\n'
 '\t   Housing manure            0.001       0     0.000       0       0.2        32\n'
 '\t   Manure storage            0.019       4     0.003       1       1.2       238\n'
 '\t   Field / grazing           0.056      11     0.004       1       1.6       328\n'
 '\t      Total farm             0.065      13     0.010       2       3.7       734\n'
 '\n' '\tMethane\n'
 '\t   Animal                    0.525     105     0.453      91     165.2     33035\n'
 '\t   Housing manure            0.100      20     0.028       6      10.1      2027\n'
 '\t   Manure storage            0.198      40     0.061      12      22.2      4440\n'
 '\t   Field application         0.017       3     0.004       1       1.6       311\n'
 '\t      Total farm             0.683     137     0.545     109     199.1     39813\n'
 '\n' '\tNitrous Oxide\n'
 '\t   Animal                    0.001       0     0.000       0       0.2        36\n'
 '\t   Housing manure            0.007       1     0.002       0       0.6       119\n'
 '\t   Farmland                  0.021       4     0.004       1       1.4       288\n'
 '\t   Indirect sources          0.004       1     0.004       1       1.5       302\n'
 '\t      Total farm             0.027       5     0.010       2       3.7       744\n'
 '\n' '\tBiogenic Carbon Dioxide\n'
 '\t   Housing facility         15.766    3153     7.435    1487    2713.8    542758\n'
 '\t   Manure storage            1.453     291     0.440      88     160.4     32086\n'
 '\t   Grazing                  11.593    2319     6.615    1323    2414.4    482885\n'
 '\t   Net land and feed           ---     ---   -20.644   -4129   -7534.9  -1506981\n'
 '\t      Total farm               ---     ---    -6.154   -1231   -2246.3   -449254\n'
 '\n'
 '\tAnthropogenic Carbon Dioxide   ---     ---     1.496     299     546.1    109229\n'
 '\n' '\n' '\n'
 '\tEnvironmental footprints of water, nitrogen, energy and carbon for a dairy farm\n'
 '\twith 200 cows and 129 other stock on 85 hectares of land.\n' '\n'
 '\t                                               Unit          Mean          SD\n'
 '\n' '\tWater Use\n'
 '\t   Feed production, rainfall                    Mg          596423       37417\n'
 '\t   Evapotranspiration                           Mg          564142       33732\n'
 '\t   Drinking                                     Mg            6033          34\n'
 '\t   Animal cooling and dust control              Mg              52          34\n'
 '\t   Parlor and equipment cleaning                Mg            1825           0\n'
 '\t   Production of purchased feed and inputs      Mg          478540       36824\n'
 '\t   Not allocated to milk production             Mg          -44458        3393\n'
 '\t      Green water footprint                 kg/kg FPCM         639          11\n'
 '\t      Blue water footprint                  kg/kg FPCM       223.5        17.0\n'
 '\n' '\tReactive Nitrogen Loss\n'
 '\t   Ammonia emission                             kg           10953         695\n'
 '\t   Nitrate leaching and runoff                  kg           11649        2415\n'
 '\t   De/nitrification emissions                   kg            4001         462\n'
 '\t   Fuel combustion emissions                    kg              82           1\n'
 '\t   Production of resource inputs                kg            3010          27\n'
 '\t   Not allocated to milk production             kg           -2877         240\n'
 '\t      Reactive nitrogen footprint            g/kg FPCM       13.56        1.21\n'
 '\n' '\tEnergy Use\n'
 '\t   Feed production                              MJ          117592        2857\n'
 '\t   Animal feeding                               MJ          104097        3164\n'
 '\t   Manure handling                              MJ           48747         520\n'
 '\t   Milking and milk cooling                     MJ          389252         678\n'
 '\t   Animal housing ventilation and lighting      MJ           70927           0\n'
 '\t   Production of resource inputs                MJ         4082577       95273\n'
 '\t   Not allocated to milk production             MJ         -465426        8939\n'
 '\t      Energy footprint                       MJ/kg FPCM       2.20        0.04\n'
 '\n' '\tGreenhouse Gas Emissions (CO2e)\n'
 '\t   Animal emissions                             kg          934537        3234\n'
 '\t   Manure emissions                             kg          221202       16093\n'
 '\t   Direct and indirect land emissions           kg          156165       14333\n'
 '\t   Net biogenic carbon dioxide emissions        kg         -449254           0\n'
 '\t   Anthropogenic carbon dioxide emissions       kg          109229         374\n'
 '\t   Production of resource inputs                kg          466848        8311\n'
 '\t   Not allocated to milk production             kg         -186851        2605\n'
 '\t      Carbon footprint without biogenic CO2  kg/kg FPCM      0.860        0.01\n'
 '\t      Carbon footprint with biogenic CO2     kg/kg FPCM      0.654        0.01\n'
 '\tFPCM is fat and protein corrected milk (4.0% fat and 3.3% protein)']

In [282]:
# try to use a for loop to go over and split based on anything more 

f = open("IFSM_srm1.txt", 'r')
# get all lines
lines = f.readlines()
str_new = []
str_test = lines[12:15]
print(str_test)
for lin in range(len(str_test)):
    str_test[lin].replace('\t', " ")
    str_test[lin].replace('\n'," ")
    print(str_test[lin])
    str_new.append([])
    for obj in str_test[lin].split("  "):
        #print(obj)
        str_new[lin].append(obj)
print(str_new)

['\t  Cutting 1       3.92       15.6       44.8          3.69       16.0       47.7\n', '\t  Cutting 2       2.56       18.6       42.8          2.46       18.8       44.2\n', '\t    Total         6.48       16.8       44.1          6.15       17.4       46.0\n']
	  Cutting 1       3.92       15.6       44.8          3.69       16.0       47.7

	  Cutting 2       2.56       18.6       42.8          2.46       18.8       44.2

	    Total         6.48       16.8       44.1          6.15       17.4       46.0

[['\t', 'Cutting 1', '', '', ' 3.92', '', '', ' 15.6', '', '', ' 44.8', '', '', '', '', '3.69', '', '', ' 16.0', '', '', ' 47.7\n'], ['\t', 'Cutting 2', '', '', ' 2.56', '', '', ' 18.6', '', '', ' 42.8', '', '', '', '', '2.46', '', '', ' 18.8', '', '', ' 44.2\n'], ['\t', '', 'Total', '', '', '', ' 6.48', '', '', ' 16.8', '', '', ' 44.1', '', '', '', '', '6.15', '', '', ' 17.4', '', '', ' 46.0\n']]